// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CvtColor.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CvtColor::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic CvtColor::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> CvtColor::ap_ST_fsm_state1 = "1";
const sc_lv<4> CvtColor::ap_ST_fsm_state2 = "10";
const sc_lv<4> CvtColor::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> CvtColor::ap_ST_fsm_state10 = "1000";
const bool CvtColor::ap_const_boolean_1 = true;
const sc_lv<32> CvtColor::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> CvtColor::ap_const_lv32_2 = "10";
const bool CvtColor::ap_const_boolean_0 = false;
const sc_lv<1> CvtColor::ap_const_lv1_0 = "0";
const sc_lv<32> CvtColor::ap_const_lv32_1 = "1";
const sc_lv<1> CvtColor::ap_const_lv1_1 = "1";
const sc_lv<10> CvtColor::ap_const_lv10_0 = "0000000000";
const sc_lv<32> CvtColor::ap_const_lv32_3 = "11";
const sc_lv<9> CvtColor::ap_const_lv9_0 = "000000000";
const sc_lv<10> CvtColor::ap_const_lv10_1 = "1";
const sc_lv<9> CvtColor::ap_const_lv9_1 = "1";
const sc_lv<32> CvtColor::ap_const_lv32_16 = "10110";
const sc_lv<32> CvtColor::ap_const_lv32_1D = "11101";
const sc_lv<32> CvtColor::ap_const_lv32_15 = "10101";
const sc_lv<32> CvtColor::ap_const_lv32_7 = "111";
const sc_lv<8> CvtColor::ap_const_lv8_FF = "11111111";
const sc_lv<32> CvtColor::ap_const_lv32_1F = "11111";
const sc_lv<32> CvtColor::ap_const_lv32_1E = "11110";
const sc_lv<2> CvtColor::ap_const_lv2_3 = "11";
const sc_lv<2> CvtColor::ap_const_lv2_0 = "00";
const sc_lv<8> CvtColor::ap_const_lv8_0 = "00000000";
const sc_lv<29> CvtColor::ap_const_lv29_1322D0 = "100110010001011010000";
const sc_lv<30> CvtColor::ap_const_lv30_259168 = "1001011001000101101000";
const sc_lv<28> CvtColor::ap_const_lv28_74BC6 = "1110100101111000110";
const sc_lv<32> CvtColor::ap_const_lv32_2DA1CA = "1011011010000111001010";
const sc_lv<32> CvtColor::ap_const_lv32_20000000 = "100000000000000000000000000000";
const sc_lv<32> CvtColor::ap_const_lv32_241893 = "1001000001100010010011";

CvtColor::CvtColor(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ImgProcess_Top_mubkb_U17 = new ImgProcess_Top_mubkb<1,1,8,22,29>("ImgProcess_Top_mubkb_U17");
    ImgProcess_Top_mubkb_U17->din0(r_V_4_i_i_fu_644_p0);
    ImgProcess_Top_mubkb_U17->din1(r_V_4_i_i_fu_644_p1);
    ImgProcess_Top_mubkb_U17->dout(r_V_4_i_i_fu_644_p2);
    ImgProcess_Top_macud_U18 = new ImgProcess_Top_macud<1,1,8,23,29,30>("ImgProcess_Top_macud_U18");
    ImgProcess_Top_macud_U18->din0(grp_fu_650_p0);
    ImgProcess_Top_macud_U18->din1(grp_fu_650_p1);
    ImgProcess_Top_macud_U18->din2(grp_fu_650_p2);
    ImgProcess_Top_macud_U18->dout(grp_fu_650_p3);
    ImgProcess_Top_madEe_U19 = new ImgProcess_Top_madEe<1,1,8,20,29,29>("ImgProcess_Top_madEe_U19");
    ImgProcess_Top_madEe_U19->din0(grp_fu_660_p0);
    ImgProcess_Top_madEe_U19->din1(grp_fu_660_p1);
    ImgProcess_Top_madEe_U19->din2(r_V_4_i_i_reg_739);
    ImgProcess_Top_madEe_U19->dout(grp_fu_660_p3);
    ImgProcess_Top_maeOg_U20 = new ImgProcess_Top_maeOg<1,1,9,23,31,32>("ImgProcess_Top_maeOg_U20");
    ImgProcess_Top_maeOg_U20->din0(i_op_assign_3_i_reg_764);
    ImgProcess_Top_maeOg_U20->din1(grp_fu_668_p1);
    ImgProcess_Top_maeOg_U20->din2(grp_fu_668_p2);
    ImgProcess_Top_maeOg_U20->dout(grp_fu_668_p3);
    ImgProcess_Top_maeOg_U21 = new ImgProcess_Top_maeOg<1,1,9,23,31,32>("ImgProcess_Top_maeOg_U21");
    ImgProcess_Top_maeOg_U21->din0(i_op_assign_4_i_reg_769);
    ImgProcess_Top_maeOg_U21->din1(grp_fu_681_p1);
    ImgProcess_Top_maeOg_U21->din2(grp_fu_681_p2);
    ImgProcess_Top_maeOg_U21->dout(grp_fu_681_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Range1_all_ones_1_fu_494_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter4_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_45_i_fu_485_p4 );

    SC_METHOD(thread_Range1_all_ones_fu_390_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter4_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_i_125_fu_381_p4 );

    SC_METHOD(thread_Range1_all_zeros_1_fu_500_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter4_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_45_i_fu_485_p4 );

    SC_METHOD(thread_Range1_all_zeros_fu_396_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_reg_pp0_iter4_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_i_125_fu_381_p4 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_1_i_blk_n);
    sensitive << ( YCrCb_IMG_data_strea_1_i_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_1_i_din);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( brmerge_i_i_i_i_fu_556_p2 );
    sensitive << ( p_mux_i_i1_i_i_fu_562_p3 );
    sensitive << ( p_i_i_i_i_fu_569_p3 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_1_i_write);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_2_i_blk_n);
    sensitive << ( YCrCb_IMG_data_strea_2_i_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_2_i_din);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( brmerge_i_i22_i_i_fu_615_p2 );
    sensitive << ( p_mux_i_i23_i_i_fu_621_p3 );
    sensitive << ( p_i_i24_i_i_fu_628_p3 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_2_i_write);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_i_blk_n);
    sensitive << ( YCrCb_IMG_data_strea_i_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_i_din);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );
    sensitive << ( ap_reg_pp0_iter5_p_Val2_s_reg_759 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_YCrCb_IMG_data_strea_i_write);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( src_mat_data_stream_s_empty_n );
    sensitive << ( src_mat_data_stream_1_empty_n );
    sensitive << ( src_mat_data_stream_2_empty_n );
    sensitive << ( YCrCb_IMG_data_strea_i_full_n );
    sensitive << ( YCrCb_IMG_data_strea_1_i_full_n );
    sensitive << ( YCrCb_IMG_data_strea_2_i_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( src_mat_data_stream_s_empty_n );
    sensitive << ( src_mat_data_stream_1_empty_n );
    sensitive << ( src_mat_data_stream_2_empty_n );
    sensitive << ( YCrCb_IMG_data_strea_i_full_n );
    sensitive << ( YCrCb_IMG_data_strea_1_i_full_n );
    sensitive << ( YCrCb_IMG_data_strea_2_i_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( src_mat_data_stream_s_empty_n );
    sensitive << ( src_mat_data_stream_1_empty_n );
    sensitive << ( src_mat_data_stream_2_empty_n );
    sensitive << ( YCrCb_IMG_data_strea_i_full_n );
    sensitive << ( YCrCb_IMG_data_strea_1_i_full_n );
    sensitive << ( YCrCb_IMG_data_strea_2_i_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( src_mat_data_stream_s_empty_n );
    sensitive << ( src_mat_data_stream_1_empty_n );
    sensitive << ( src_mat_data_stream_2_empty_n );
    sensitive << ( exitcond_i_reg_713 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter6);
    sensitive << ( YCrCb_IMG_data_strea_i_full_n );
    sensitive << ( YCrCb_IMG_data_strea_1_i_full_n );
    sensitive << ( YCrCb_IMG_data_strea_2_i_full_n );
    sensitive << ( ap_reg_pp0_iter5_exitcond_i_reg_713 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( exitcond_i_fu_214_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond1_i_fu_203_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_brmerge_i_i22_i_i_fu_615_p2);
    sensitive << ( neg_src_not_i_i19_i_s_fu_600_p2 );
    sensitive << ( p_39_demorgan_i_not_i_1_fu_610_p2 );

    SC_METHOD(thread_brmerge_i_i_i_i_fu_556_p2);
    sensitive << ( neg_src_not_i_i_i_i_fu_541_p2 );
    sensitive << ( p_39_demorgan_i_not_i_fu_551_p2 );

    SC_METHOD(thread_brmerge_i_i_not_i_i2_fu_605_p2);
    sensitive << ( p_39_demorgan_i_i_i17_reg_816 );
    sensitive << ( neg_src_not_i_i19_i_s_fu_600_p2 );

    SC_METHOD(thread_brmerge_i_i_not_i_i_s_fu_546_p2);
    sensitive << ( p_39_demorgan_i_i_i_i_reg_792 );
    sensitive << ( neg_src_not_i_i_i_i_fu_541_p2 );

    SC_METHOD(thread_carry_1_fu_479_p2);
    sensitive << ( tmp_71_fu_452_p3 );
    sensitive << ( tmp_24_i_i9_i_i_fu_473_p2 );

    SC_METHOD(thread_carry_fu_375_p2);
    sensitive << ( tmp_67_fu_348_p3 );
    sensitive << ( tmp_24_i_i_i_i_fu_369_p2 );

    SC_METHOD(thread_cols_1_fu_199_p1);
    sensitive << ( cols );

    SC_METHOD(thread_deleted_zeros_1_fu_506_p3);
    sensitive << ( carry_1_fu_479_p2 );
    sensitive << ( Range1_all_ones_1_fu_494_p2 );
    sensitive << ( Range1_all_zeros_1_fu_500_p2 );

    SC_METHOD(thread_deleted_zeros_fu_402_p3);
    sensitive << ( carry_fu_375_p2 );
    sensitive << ( Range1_all_ones_fu_390_p2 );
    sensitive << ( Range1_all_zeros_fu_396_p2 );

    SC_METHOD(thread_exitcond1_i_fu_203_p2);
    sensitive << ( rows_1_fu_195_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_i_reg_173 );

    SC_METHOD(thread_exitcond_i_fu_214_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( j_i_reg_184 );
    sensitive << ( cols_1_fu_199_p1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_650_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter2_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( grp_fu_650_p00 );

    SC_METHOD(thread_grp_fu_650_p00);
    sensitive << ( ap_reg_pp0_iter2_tmp_77_reg_728 );

    SC_METHOD(thread_grp_fu_650_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter2_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_grp_fu_650_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter2_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( grp_fu_650_p20 );

    SC_METHOD(thread_grp_fu_650_p20);
    sensitive << ( grp_fu_660_p3 );

    SC_METHOD(thread_grp_fu_660_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter2_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( grp_fu_660_p00 );

    SC_METHOD(thread_grp_fu_660_p00);
    sensitive << ( ap_reg_pp0_iter2_tmp_78_reg_733 );

    SC_METHOD(thread_grp_fu_660_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter2_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_grp_fu_668_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter4_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_grp_fu_668_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter4_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_grp_fu_681_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter4_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_grp_fu_681_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter4_exitcond_i_reg_713 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_i_fu_208_p2);
    sensitive << ( i_i_reg_173 );

    SC_METHOD(thread_i_op_assign_3_i_fu_303_p2);
    sensitive << ( tmp_30_cast_i_i_fu_296_p1 );
    sensitive << ( tmp_31_cast_i_i_fu_299_p1 );

    SC_METHOD(thread_i_op_assign_4_i_fu_312_p2);
    sensitive << ( tmp_31_cast_i_i_fu_299_p1 );
    sensitive << ( tmp_33_cast_i_i_fu_309_p1 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( exitcond1_i_fu_203_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j_fu_219_p2);
    sensitive << ( j_i_reg_184 );

    SC_METHOD(thread_neg_src_4_fu_590_p2);
    sensitive << ( signbit_1_reg_798 );
    sensitive << ( tmp_25_i_i15_i_i_fu_585_p2 );

    SC_METHOD(thread_neg_src_fu_531_p2);
    sensitive << ( signbit_reg_774 );
    sensitive << ( tmp_25_i_i_i_i_fu_526_p2 );

    SC_METHOD(thread_neg_src_not_i_i19_i_s_fu_600_p2);
    sensitive << ( p_38_i_i_i14_i_i_reg_810 );
    sensitive << ( signbit_not_i18_i_i_fu_595_p2 );

    SC_METHOD(thread_neg_src_not_i_i_i_i_fu_541_p2);
    sensitive << ( p_38_i_i_i_i_i_reg_786 );
    sensitive << ( signbit_not_i_i_i_fu_536_p2 );

    SC_METHOD(thread_not_carry_i_i_fu_282_p2);
    sensitive << ( tmp_64_fu_268_p3 );
    sensitive << ( p_Result_9_i_i_not_fu_276_p2 );

    SC_METHOD(thread_p_38_i_i_i14_i_i_fu_514_p2);
    sensitive << ( carry_1_fu_479_p2 );
    sensitive << ( Range1_all_ones_1_fu_494_p2 );

    SC_METHOD(thread_p_38_i_i_i_i_i_fu_410_p2);
    sensitive << ( carry_fu_375_p2 );
    sensitive << ( Range1_all_ones_fu_390_p2 );

    SC_METHOD(thread_p_39_demorgan_i_i_i17_fu_520_p2);
    sensitive << ( signbit_1_fu_425_p3 );
    sensitive << ( deleted_zeros_1_fu_506_p3 );

    SC_METHOD(thread_p_39_demorgan_i_i_i_i_fu_416_p2);
    sensitive << ( signbit_fu_321_p3 );
    sensitive << ( deleted_zeros_fu_402_p3 );

    SC_METHOD(thread_p_39_demorgan_i_not_i_1_fu_610_p2);
    sensitive << ( p_39_demorgan_i_i_i17_reg_816 );

    SC_METHOD(thread_p_39_demorgan_i_not_i_fu_551_p2);
    sensitive << ( p_39_demorgan_i_i_i_i_reg_792 );

    SC_METHOD(thread_p_Result_9_i_i_not_fu_276_p2);
    sensitive << ( tmp_63_fu_256_p3 );

    SC_METHOD(thread_p_Val2_13_fu_328_p4);
    sensitive << ( grp_fu_668_p3 );

    SC_METHOD(thread_p_Val2_14_fu_355_p2);
    sensitive << ( p_Val2_13_fu_328_p4 );
    sensitive << ( tmp_23_i_i_i_i_fu_344_p1 );

    SC_METHOD(thread_p_Val2_18_fu_432_p4);
    sensitive << ( grp_fu_681_p3 );

    SC_METHOD(thread_p_Val2_19_fu_459_p2);
    sensitive << ( p_Val2_18_fu_432_p4 );
    sensitive << ( tmp_23_i_i5_i_i_fu_448_p1 );

    SC_METHOD(thread_p_Val2_9_fu_263_p2);
    sensitive << ( p_Val2_8_reg_749 );
    sensitive << ( tmp_26_i_i_i_i_fu_253_p1 );

    SC_METHOD(thread_p_Val2_s_fu_288_p3);
    sensitive << ( p_Val2_9_fu_263_p2 );
    sensitive << ( not_carry_i_i_fu_282_p2 );

    SC_METHOD(thread_p_i_i24_i_i_fu_628_p3);
    sensitive << ( p_Val2_19_reg_804 );
    sensitive << ( neg_src_4_fu_590_p2 );

    SC_METHOD(thread_p_i_i_i_i_fu_569_p3);
    sensitive << ( p_Val2_14_reg_780 );
    sensitive << ( neg_src_fu_531_p2 );

    SC_METHOD(thread_p_mux_i_i1_i_i_fu_562_p3);
    sensitive << ( p_Val2_14_reg_780 );
    sensitive << ( brmerge_i_i_not_i_i_s_fu_546_p2 );

    SC_METHOD(thread_p_mux_i_i23_i_i_fu_621_p3);
    sensitive << ( p_Val2_19_reg_804 );
    sensitive << ( brmerge_i_i_not_i_i2_fu_605_p2 );

    SC_METHOD(thread_r_V_4_i_i_fu_644_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( r_V_4_i_i_fu_644_p00 );

    SC_METHOD(thread_r_V_4_i_i_fu_644_p00);
    sensitive << ( tmp_76_reg_722 );

    SC_METHOD(thread_r_V_4_i_i_fu_644_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_rows_1_fu_195_p1);
    sensitive << ( rows );

    SC_METHOD(thread_signbit_1_fu_425_p3);
    sensitive << ( grp_fu_681_p3 );

    SC_METHOD(thread_signbit_fu_321_p3);
    sensitive << ( grp_fu_668_p3 );

    SC_METHOD(thread_signbit_not_i18_i_i_fu_595_p2);
    sensitive << ( signbit_1_reg_798 );

    SC_METHOD(thread_signbit_not_i_i_i_fu_536_p2);
    sensitive << ( signbit_reg_774 );

    SC_METHOD(thread_src_mat_data_stream_1_blk_n);
    sensitive << ( src_mat_data_stream_1_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_reg_713 );

    SC_METHOD(thread_src_mat_data_stream_1_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_713 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_src_mat_data_stream_2_blk_n);
    sensitive << ( src_mat_data_stream_2_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_reg_713 );

    SC_METHOD(thread_src_mat_data_stream_2_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_713 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_src_mat_data_stream_s_blk_n);
    sensitive << ( src_mat_data_stream_s_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_reg_713 );

    SC_METHOD(thread_src_mat_data_stream_s_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_713 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_23_i_i5_i_i_fu_448_p1);
    sensitive << ( tmp_70_fu_441_p3 );

    SC_METHOD(thread_tmp_23_i_i_i_i_fu_344_p1);
    sensitive << ( tmp_66_fu_337_p3 );

    SC_METHOD(thread_tmp_24_i_i9_i_i_fu_473_p2);
    sensitive << ( tmp_72_fu_465_p3 );

    SC_METHOD(thread_tmp_24_i_i_i_i_fu_369_p2);
    sensitive << ( tmp_68_fu_361_p3 );

    SC_METHOD(thread_tmp_25_i_i15_i_i_fu_585_p2);
    sensitive << ( p_38_i_i_i14_i_i_reg_810 );

    SC_METHOD(thread_tmp_25_i_i_i_i_fu_526_p2);
    sensitive << ( p_38_i_i_i_i_i_reg_786 );

    SC_METHOD(thread_tmp_26_i_i_i_i_fu_253_p1);
    sensitive << ( tmp_reg_754 );

    SC_METHOD(thread_tmp_30_cast_i_i_fu_296_p1);
    sensitive << ( ap_reg_pp0_iter3_tmp_76_reg_722 );

    SC_METHOD(thread_tmp_31_cast_i_i_fu_299_p1);
    sensitive << ( p_Val2_s_fu_288_p3 );

    SC_METHOD(thread_tmp_33_cast_i_i_fu_309_p1);
    sensitive << ( ap_reg_pp0_iter3_tmp_78_reg_733 );

    SC_METHOD(thread_tmp_45_i_fu_485_p4);
    sensitive << ( grp_fu_681_p3 );

    SC_METHOD(thread_tmp_63_fu_256_p3);
    sensitive << ( r_V_1_reg_744 );

    SC_METHOD(thread_tmp_64_fu_268_p3);
    sensitive << ( p_Val2_9_fu_263_p2 );

    SC_METHOD(thread_tmp_66_fu_337_p3);
    sensitive << ( grp_fu_668_p3 );

    SC_METHOD(thread_tmp_67_fu_348_p3);
    sensitive << ( grp_fu_668_p3 );

    SC_METHOD(thread_tmp_68_fu_361_p3);
    sensitive << ( p_Val2_14_fu_355_p2 );

    SC_METHOD(thread_tmp_70_fu_441_p3);
    sensitive << ( grp_fu_681_p3 );

    SC_METHOD(thread_tmp_71_fu_452_p3);
    sensitive << ( grp_fu_681_p3 );

    SC_METHOD(thread_tmp_72_fu_465_p3);
    sensitive << ( p_Val2_19_fu_459_p2 );

    SC_METHOD(thread_tmp_i_125_fu_381_p4);
    sensitive << ( grp_fu_668_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( exitcond1_i_fu_203_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i_fu_214_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CvtColor_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, src_mat_data_stream_s_dout, "(port)src_mat_data_stream_s_dout");
    sc_trace(mVcdFile, src_mat_data_stream_s_empty_n, "(port)src_mat_data_stream_s_empty_n");
    sc_trace(mVcdFile, src_mat_data_stream_s_read, "(port)src_mat_data_stream_s_read");
    sc_trace(mVcdFile, src_mat_data_stream_1_dout, "(port)src_mat_data_stream_1_dout");
    sc_trace(mVcdFile, src_mat_data_stream_1_empty_n, "(port)src_mat_data_stream_1_empty_n");
    sc_trace(mVcdFile, src_mat_data_stream_1_read, "(port)src_mat_data_stream_1_read");
    sc_trace(mVcdFile, src_mat_data_stream_2_dout, "(port)src_mat_data_stream_2_dout");
    sc_trace(mVcdFile, src_mat_data_stream_2_empty_n, "(port)src_mat_data_stream_2_empty_n");
    sc_trace(mVcdFile, src_mat_data_stream_2_read, "(port)src_mat_data_stream_2_read");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_i_din, "(port)YCrCb_IMG_data_strea_i_din");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_i_full_n, "(port)YCrCb_IMG_data_strea_i_full_n");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_i_write, "(port)YCrCb_IMG_data_strea_i_write");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_1_i_din, "(port)YCrCb_IMG_data_strea_1_i_din");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_1_i_full_n, "(port)YCrCb_IMG_data_strea_1_i_full_n");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_1_i_write, "(port)YCrCb_IMG_data_strea_1_i_write");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_2_i_din, "(port)YCrCb_IMG_data_strea_2_i_din");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_2_i_full_n, "(port)YCrCb_IMG_data_strea_2_i_full_n");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_2_i_write, "(port)YCrCb_IMG_data_strea_2_i_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, src_mat_data_stream_s_blk_n, "src_mat_data_stream_s_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_i_reg_713, "exitcond_i_reg_713");
    sc_trace(mVcdFile, src_mat_data_stream_1_blk_n, "src_mat_data_stream_1_blk_n");
    sc_trace(mVcdFile, src_mat_data_stream_2_blk_n, "src_mat_data_stream_2_blk_n");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_i_blk_n, "YCrCb_IMG_data_strea_i_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_pp0_iter5_exitcond_i_reg_713, "ap_reg_pp0_iter5_exitcond_i_reg_713");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_1_i_blk_n, "YCrCb_IMG_data_strea_1_i_blk_n");
    sc_trace(mVcdFile, YCrCb_IMG_data_strea_2_i_blk_n, "YCrCb_IMG_data_strea_2_i_blk_n");
    sc_trace(mVcdFile, j_i_reg_184, "j_i_reg_184");
    sc_trace(mVcdFile, rows_1_fu_195_p1, "rows_1_fu_195_p1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, cols_1_fu_199_p1, "cols_1_fu_199_p1");
    sc_trace(mVcdFile, exitcond1_i_fu_203_p2, "exitcond1_i_fu_203_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_208_p2, "i_fu_208_p2");
    sc_trace(mVcdFile, i_reg_708, "i_reg_708");
    sc_trace(mVcdFile, exitcond_i_fu_214_p2, "exitcond_i_fu_214_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter4, "ap_block_state7_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter5, "ap_block_state8_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter6, "ap_block_state9_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_exitcond_i_reg_713, "ap_reg_pp0_iter1_exitcond_i_reg_713");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_exitcond_i_reg_713, "ap_reg_pp0_iter2_exitcond_i_reg_713");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_exitcond_i_reg_713, "ap_reg_pp0_iter3_exitcond_i_reg_713");
    sc_trace(mVcdFile, ap_reg_pp0_iter4_exitcond_i_reg_713, "ap_reg_pp0_iter4_exitcond_i_reg_713");
    sc_trace(mVcdFile, j_fu_219_p2, "j_fu_219_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_76_reg_722, "tmp_76_reg_722");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_tmp_76_reg_722, "ap_reg_pp0_iter2_tmp_76_reg_722");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_tmp_76_reg_722, "ap_reg_pp0_iter3_tmp_76_reg_722");
    sc_trace(mVcdFile, tmp_77_reg_728, "tmp_77_reg_728");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_tmp_77_reg_728, "ap_reg_pp0_iter2_tmp_77_reg_728");
    sc_trace(mVcdFile, tmp_78_reg_733, "tmp_78_reg_733");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_tmp_78_reg_733, "ap_reg_pp0_iter2_tmp_78_reg_733");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_tmp_78_reg_733, "ap_reg_pp0_iter3_tmp_78_reg_733");
    sc_trace(mVcdFile, r_V_4_i_i_fu_644_p2, "r_V_4_i_i_fu_644_p2");
    sc_trace(mVcdFile, r_V_4_i_i_reg_739, "r_V_4_i_i_reg_739");
    sc_trace(mVcdFile, grp_fu_650_p3, "grp_fu_650_p3");
    sc_trace(mVcdFile, r_V_1_reg_744, "r_V_1_reg_744");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, p_Val2_8_reg_749, "p_Val2_8_reg_749");
    sc_trace(mVcdFile, tmp_reg_754, "tmp_reg_754");
    sc_trace(mVcdFile, p_Val2_s_fu_288_p3, "p_Val2_s_fu_288_p3");
    sc_trace(mVcdFile, p_Val2_s_reg_759, "p_Val2_s_reg_759");
    sc_trace(mVcdFile, ap_reg_pp0_iter5_p_Val2_s_reg_759, "ap_reg_pp0_iter5_p_Val2_s_reg_759");
    sc_trace(mVcdFile, i_op_assign_3_i_fu_303_p2, "i_op_assign_3_i_fu_303_p2");
    sc_trace(mVcdFile, i_op_assign_3_i_reg_764, "i_op_assign_3_i_reg_764");
    sc_trace(mVcdFile, i_op_assign_4_i_fu_312_p2, "i_op_assign_4_i_fu_312_p2");
    sc_trace(mVcdFile, i_op_assign_4_i_reg_769, "i_op_assign_4_i_reg_769");
    sc_trace(mVcdFile, signbit_fu_321_p3, "signbit_fu_321_p3");
    sc_trace(mVcdFile, signbit_reg_774, "signbit_reg_774");
    sc_trace(mVcdFile, p_Val2_14_fu_355_p2, "p_Val2_14_fu_355_p2");
    sc_trace(mVcdFile, p_Val2_14_reg_780, "p_Val2_14_reg_780");
    sc_trace(mVcdFile, p_38_i_i_i_i_i_fu_410_p2, "p_38_i_i_i_i_i_fu_410_p2");
    sc_trace(mVcdFile, p_38_i_i_i_i_i_reg_786, "p_38_i_i_i_i_i_reg_786");
    sc_trace(mVcdFile, p_39_demorgan_i_i_i_i_fu_416_p2, "p_39_demorgan_i_i_i_i_fu_416_p2");
    sc_trace(mVcdFile, p_39_demorgan_i_i_i_i_reg_792, "p_39_demorgan_i_i_i_i_reg_792");
    sc_trace(mVcdFile, signbit_1_fu_425_p3, "signbit_1_fu_425_p3");
    sc_trace(mVcdFile, signbit_1_reg_798, "signbit_1_reg_798");
    sc_trace(mVcdFile, p_Val2_19_fu_459_p2, "p_Val2_19_fu_459_p2");
    sc_trace(mVcdFile, p_Val2_19_reg_804, "p_Val2_19_reg_804");
    sc_trace(mVcdFile, p_38_i_i_i14_i_i_fu_514_p2, "p_38_i_i_i14_i_i_fu_514_p2");
    sc_trace(mVcdFile, p_38_i_i_i14_i_i_reg_810, "p_38_i_i_i14_i_i_reg_810");
    sc_trace(mVcdFile, p_39_demorgan_i_i_i17_fu_520_p2, "p_39_demorgan_i_i_i17_fu_520_p2");
    sc_trace(mVcdFile, p_39_demorgan_i_i_i17_reg_816, "p_39_demorgan_i_i_i17_reg_816");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, i_i_reg_173, "i_i_reg_173");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, grp_fu_660_p3, "grp_fu_660_p3");
    sc_trace(mVcdFile, tmp_26_i_i_i_i_fu_253_p1, "tmp_26_i_i_i_i_fu_253_p1");
    sc_trace(mVcdFile, p_Val2_9_fu_263_p2, "p_Val2_9_fu_263_p2");
    sc_trace(mVcdFile, tmp_63_fu_256_p3, "tmp_63_fu_256_p3");
    sc_trace(mVcdFile, tmp_64_fu_268_p3, "tmp_64_fu_268_p3");
    sc_trace(mVcdFile, p_Result_9_i_i_not_fu_276_p2, "p_Result_9_i_i_not_fu_276_p2");
    sc_trace(mVcdFile, not_carry_i_i_fu_282_p2, "not_carry_i_i_fu_282_p2");
    sc_trace(mVcdFile, tmp_30_cast_i_i_fu_296_p1, "tmp_30_cast_i_i_fu_296_p1");
    sc_trace(mVcdFile, tmp_31_cast_i_i_fu_299_p1, "tmp_31_cast_i_i_fu_299_p1");
    sc_trace(mVcdFile, tmp_33_cast_i_i_fu_309_p1, "tmp_33_cast_i_i_fu_309_p1");
    sc_trace(mVcdFile, grp_fu_668_p3, "grp_fu_668_p3");
    sc_trace(mVcdFile, tmp_66_fu_337_p3, "tmp_66_fu_337_p3");
    sc_trace(mVcdFile, p_Val2_13_fu_328_p4, "p_Val2_13_fu_328_p4");
    sc_trace(mVcdFile, tmp_23_i_i_i_i_fu_344_p1, "tmp_23_i_i_i_i_fu_344_p1");
    sc_trace(mVcdFile, tmp_68_fu_361_p3, "tmp_68_fu_361_p3");
    sc_trace(mVcdFile, tmp_67_fu_348_p3, "tmp_67_fu_348_p3");
    sc_trace(mVcdFile, tmp_24_i_i_i_i_fu_369_p2, "tmp_24_i_i_i_i_fu_369_p2");
    sc_trace(mVcdFile, tmp_i_125_fu_381_p4, "tmp_i_125_fu_381_p4");
    sc_trace(mVcdFile, carry_fu_375_p2, "carry_fu_375_p2");
    sc_trace(mVcdFile, Range1_all_ones_fu_390_p2, "Range1_all_ones_fu_390_p2");
    sc_trace(mVcdFile, Range1_all_zeros_fu_396_p2, "Range1_all_zeros_fu_396_p2");
    sc_trace(mVcdFile, deleted_zeros_fu_402_p3, "deleted_zeros_fu_402_p3");
    sc_trace(mVcdFile, grp_fu_681_p3, "grp_fu_681_p3");
    sc_trace(mVcdFile, tmp_70_fu_441_p3, "tmp_70_fu_441_p3");
    sc_trace(mVcdFile, p_Val2_18_fu_432_p4, "p_Val2_18_fu_432_p4");
    sc_trace(mVcdFile, tmp_23_i_i5_i_i_fu_448_p1, "tmp_23_i_i5_i_i_fu_448_p1");
    sc_trace(mVcdFile, tmp_72_fu_465_p3, "tmp_72_fu_465_p3");
    sc_trace(mVcdFile, tmp_71_fu_452_p3, "tmp_71_fu_452_p3");
    sc_trace(mVcdFile, tmp_24_i_i9_i_i_fu_473_p2, "tmp_24_i_i9_i_i_fu_473_p2");
    sc_trace(mVcdFile, tmp_45_i_fu_485_p4, "tmp_45_i_fu_485_p4");
    sc_trace(mVcdFile, carry_1_fu_479_p2, "carry_1_fu_479_p2");
    sc_trace(mVcdFile, Range1_all_ones_1_fu_494_p2, "Range1_all_ones_1_fu_494_p2");
    sc_trace(mVcdFile, Range1_all_zeros_1_fu_500_p2, "Range1_all_zeros_1_fu_500_p2");
    sc_trace(mVcdFile, deleted_zeros_1_fu_506_p3, "deleted_zeros_1_fu_506_p3");
    sc_trace(mVcdFile, tmp_25_i_i_i_i_fu_526_p2, "tmp_25_i_i_i_i_fu_526_p2");
    sc_trace(mVcdFile, signbit_not_i_i_i_fu_536_p2, "signbit_not_i_i_i_fu_536_p2");
    sc_trace(mVcdFile, neg_src_not_i_i_i_i_fu_541_p2, "neg_src_not_i_i_i_i_fu_541_p2");
    sc_trace(mVcdFile, p_39_demorgan_i_not_i_fu_551_p2, "p_39_demorgan_i_not_i_fu_551_p2");
    sc_trace(mVcdFile, brmerge_i_i_not_i_i_s_fu_546_p2, "brmerge_i_i_not_i_i_s_fu_546_p2");
    sc_trace(mVcdFile, neg_src_fu_531_p2, "neg_src_fu_531_p2");
    sc_trace(mVcdFile, brmerge_i_i_i_i_fu_556_p2, "brmerge_i_i_i_i_fu_556_p2");
    sc_trace(mVcdFile, p_mux_i_i1_i_i_fu_562_p3, "p_mux_i_i1_i_i_fu_562_p3");
    sc_trace(mVcdFile, p_i_i_i_i_fu_569_p3, "p_i_i_i_i_fu_569_p3");
    sc_trace(mVcdFile, tmp_25_i_i15_i_i_fu_585_p2, "tmp_25_i_i15_i_i_fu_585_p2");
    sc_trace(mVcdFile, signbit_not_i18_i_i_fu_595_p2, "signbit_not_i18_i_i_fu_595_p2");
    sc_trace(mVcdFile, neg_src_not_i_i19_i_s_fu_600_p2, "neg_src_not_i_i19_i_s_fu_600_p2");
    sc_trace(mVcdFile, p_39_demorgan_i_not_i_1_fu_610_p2, "p_39_demorgan_i_not_i_1_fu_610_p2");
    sc_trace(mVcdFile, brmerge_i_i_not_i_i2_fu_605_p2, "brmerge_i_i_not_i_i2_fu_605_p2");
    sc_trace(mVcdFile, neg_src_4_fu_590_p2, "neg_src_4_fu_590_p2");
    sc_trace(mVcdFile, brmerge_i_i22_i_i_fu_615_p2, "brmerge_i_i22_i_i_fu_615_p2");
    sc_trace(mVcdFile, p_mux_i_i23_i_i_fu_621_p3, "p_mux_i_i23_i_i_fu_621_p3");
    sc_trace(mVcdFile, p_i_i24_i_i_fu_628_p3, "p_i_i24_i_i_fu_628_p3");
    sc_trace(mVcdFile, r_V_4_i_i_fu_644_p0, "r_V_4_i_i_fu_644_p0");
    sc_trace(mVcdFile, r_V_4_i_i_fu_644_p1, "r_V_4_i_i_fu_644_p1");
    sc_trace(mVcdFile, grp_fu_650_p0, "grp_fu_650_p0");
    sc_trace(mVcdFile, grp_fu_650_p1, "grp_fu_650_p1");
    sc_trace(mVcdFile, grp_fu_650_p2, "grp_fu_650_p2");
    sc_trace(mVcdFile, grp_fu_660_p0, "grp_fu_660_p0");
    sc_trace(mVcdFile, grp_fu_660_p1, "grp_fu_660_p1");
    sc_trace(mVcdFile, grp_fu_668_p1, "grp_fu_668_p1");
    sc_trace(mVcdFile, grp_fu_668_p2, "grp_fu_668_p2");
    sc_trace(mVcdFile, grp_fu_681_p1, "grp_fu_681_p1");
    sc_trace(mVcdFile, grp_fu_681_p2, "grp_fu_681_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_650_p00, "grp_fu_650_p00");
    sc_trace(mVcdFile, grp_fu_650_p20, "grp_fu_650_p20");
    sc_trace(mVcdFile, grp_fu_660_p00, "grp_fu_660_p00");
    sc_trace(mVcdFile, r_V_4_i_i_fu_644_p00, "r_V_4_i_i_fu_644_p00");
#endif

    }
}

CvtColor::~CvtColor() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ImgProcess_Top_mubkb_U17;
    delete ImgProcess_Top_macud_U18;
    delete ImgProcess_Top_madEe_U19;
    delete ImgProcess_Top_maeOg_U20;
    delete ImgProcess_Top_maeOg_U21;
}

void CvtColor::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond1_i_fu_203_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_203_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_203_p2.read()))) {
            ap_enable_reg_pp0_iter6 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_i_reg_173 = i_reg_708.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_i_reg_173 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_214_p2.read()))) {
        j_i_reg_184 = j_fu_219_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_fu_203_p2.read()))) {
        j_i_reg_184 = ap_const_lv9_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_exitcond_i_reg_713 = exitcond_i_reg_713.read();
        exitcond_i_reg_713 = exitcond_i_fu_214_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        ap_reg_pp0_iter2_exitcond_i_reg_713 = ap_reg_pp0_iter1_exitcond_i_reg_713.read();
        ap_reg_pp0_iter2_tmp_76_reg_722 = tmp_76_reg_722.read();
        ap_reg_pp0_iter2_tmp_77_reg_728 = tmp_77_reg_728.read();
        ap_reg_pp0_iter2_tmp_78_reg_733 = tmp_78_reg_733.read();
        ap_reg_pp0_iter3_exitcond_i_reg_713 = ap_reg_pp0_iter2_exitcond_i_reg_713.read();
        ap_reg_pp0_iter3_tmp_76_reg_722 = ap_reg_pp0_iter2_tmp_76_reg_722.read();
        ap_reg_pp0_iter3_tmp_78_reg_733 = ap_reg_pp0_iter2_tmp_78_reg_733.read();
        ap_reg_pp0_iter4_exitcond_i_reg_713 = ap_reg_pp0_iter3_exitcond_i_reg_713.read();
        ap_reg_pp0_iter5_exitcond_i_reg_713 = ap_reg_pp0_iter4_exitcond_i_reg_713.read();
        ap_reg_pp0_iter5_p_Val2_s_reg_759 = p_Val2_s_reg_759.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter3_exitcond_i_reg_713.read()))) {
        i_op_assign_3_i_reg_764 = i_op_assign_3_i_fu_303_p2.read();
        i_op_assign_4_i_reg_769 = i_op_assign_4_i_fu_312_p2.read();
        p_Val2_s_reg_759 = p_Val2_s_fu_288_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_708 = i_fu_208_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter4_exitcond_i_reg_713.read()))) {
        p_38_i_i_i14_i_i_reg_810 = p_38_i_i_i14_i_i_fu_514_p2.read();
        p_38_i_i_i_i_i_reg_786 = p_38_i_i_i_i_i_fu_410_p2.read();
        p_39_demorgan_i_i_i17_reg_816 = p_39_demorgan_i_i_i17_fu_520_p2.read();
        p_39_demorgan_i_i_i_i_reg_792 = p_39_demorgan_i_i_i_i_fu_416_p2.read();
        p_Val2_14_reg_780 = p_Val2_14_fu_355_p2.read();
        p_Val2_19_reg_804 = p_Val2_19_fu_459_p2.read();
        signbit_1_reg_798 = grp_fu_681_p3.read().range(31, 31);
        signbit_reg_774 = grp_fu_668_p3.read().range(31, 31);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter2_exitcond_i_reg_713.read()))) {
        p_Val2_8_reg_749 = grp_fu_650_p3.read().range(29, 22);
        tmp_reg_754 = grp_fu_650_p3.read().range(21, 21);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter2_exitcond_i_reg_713.read()))) {
        r_V_1_reg_744 = grp_fu_650_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_reg_713.read()))) {
        r_V_4_i_i_reg_739 = r_V_4_i_i_fu_644_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_76_reg_722 = src_mat_data_stream_s_dout.read();
        tmp_77_reg_728 = src_mat_data_stream_1_dout.read();
        tmp_78_reg_733 = src_mat_data_stream_2_dout.read();
    }
}

void CvtColor::thread_Range1_all_ones_1_fu_494_p2() {
    Range1_all_ones_1_fu_494_p2 = (!tmp_45_i_fu_485_p4.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(tmp_45_i_fu_485_p4.read() == ap_const_lv2_3);
}

void CvtColor::thread_Range1_all_ones_fu_390_p2() {
    Range1_all_ones_fu_390_p2 = (!tmp_i_125_fu_381_p4.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(tmp_i_125_fu_381_p4.read() == ap_const_lv2_3);
}

void CvtColor::thread_Range1_all_zeros_1_fu_500_p2() {
    Range1_all_zeros_1_fu_500_p2 = (!tmp_45_i_fu_485_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_45_i_fu_485_p4.read() == ap_const_lv2_0);
}

void CvtColor::thread_Range1_all_zeros_fu_396_p2() {
    Range1_all_zeros_fu_396_p2 = (!tmp_i_125_fu_381_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_i_125_fu_381_p4.read() == ap_const_lv2_0);
}

void CvtColor::thread_YCrCb_IMG_data_strea_1_i_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()))) {
        YCrCb_IMG_data_strea_1_i_blk_n = YCrCb_IMG_data_strea_1_i_full_n.read();
    } else {
        YCrCb_IMG_data_strea_1_i_blk_n = ap_const_logic_1;
    }
}

void CvtColor::thread_YCrCb_IMG_data_strea_1_i_din() {
    YCrCb_IMG_data_strea_1_i_din = (!brmerge_i_i_i_i_fu_556_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_i_i_i_i_fu_556_p2.read()[0].to_bool())? p_mux_i_i1_i_i_fu_562_p3.read(): p_i_i_i_i_fu_569_p3.read());
}

void CvtColor::thread_YCrCb_IMG_data_strea_1_i_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        YCrCb_IMG_data_strea_1_i_write = ap_const_logic_1;
    } else {
        YCrCb_IMG_data_strea_1_i_write = ap_const_logic_0;
    }
}

void CvtColor::thread_YCrCb_IMG_data_strea_2_i_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()))) {
        YCrCb_IMG_data_strea_2_i_blk_n = YCrCb_IMG_data_strea_2_i_full_n.read();
    } else {
        YCrCb_IMG_data_strea_2_i_blk_n = ap_const_logic_1;
    }
}

void CvtColor::thread_YCrCb_IMG_data_strea_2_i_din() {
    YCrCb_IMG_data_strea_2_i_din = (!brmerge_i_i22_i_i_fu_615_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_i_i22_i_i_fu_615_p2.read()[0].to_bool())? p_mux_i_i23_i_i_fu_621_p3.read(): p_i_i24_i_i_fu_628_p3.read());
}

void CvtColor::thread_YCrCb_IMG_data_strea_2_i_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        YCrCb_IMG_data_strea_2_i_write = ap_const_logic_1;
    } else {
        YCrCb_IMG_data_strea_2_i_write = ap_const_logic_0;
    }
}

void CvtColor::thread_YCrCb_IMG_data_strea_i_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()))) {
        YCrCb_IMG_data_strea_i_blk_n = YCrCb_IMG_data_strea_i_full_n.read();
    } else {
        YCrCb_IMG_data_strea_i_blk_n = ap_const_logic_1;
    }
}

void CvtColor::thread_YCrCb_IMG_data_strea_i_din() {
    YCrCb_IMG_data_strea_i_din = ap_reg_pp0_iter5_p_Val2_s_reg_759.read();
}

void CvtColor::thread_YCrCb_IMG_data_strea_i_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        YCrCb_IMG_data_strea_i_write = ap_const_logic_1;
    } else {
        YCrCb_IMG_data_strea_i_write = ap_const_logic_0;
    }
}

void CvtColor::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void CvtColor::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void CvtColor::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[3];
}

void CvtColor::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void CvtColor::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_s_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_1_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_2_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_i_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_1_i_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_2_i_full_n.read())))));
}

void CvtColor::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_s_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_1_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_2_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_i_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_1_i_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_2_i_full_n.read())))));
}

void CvtColor::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_s_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_1_empty_n.read())) || 
   (esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_2_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
  ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_i_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_1_i_full_n.read())) || 
   (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
    esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_2_i_full_n.read())))));
}

void CvtColor::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void CvtColor::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_s_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_1_empty_n.read())) || (esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, src_mat_data_stream_2_empty_n.read())));
}

void CvtColor::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor::thread_ap_block_state7_pp0_stage0_iter4() {
    ap_block_state7_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor::thread_ap_block_state8_pp0_stage0_iter5() {
    ap_block_state8_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor::thread_ap_block_state9_pp0_stage0_iter6() {
    ap_block_state9_pp0_stage0_iter6 = ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_i_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_1_i_full_n.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter5_exitcond_i_reg_713.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, YCrCb_IMG_data_strea_2_i_full_n.read())));
}

void CvtColor::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(exitcond_i_fu_214_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void CvtColor::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_i_fu_203_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void CvtColor::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void CvtColor::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void CvtColor::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void CvtColor::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void CvtColor::thread_brmerge_i_i22_i_i_fu_615_p2() {
    brmerge_i_i22_i_i_fu_615_p2 = (neg_src_not_i_i19_i_s_fu_600_p2.read() | p_39_demorgan_i_not_i_1_fu_610_p2.read());
}

void CvtColor::thread_brmerge_i_i_i_i_fu_556_p2() {
    brmerge_i_i_i_i_fu_556_p2 = (neg_src_not_i_i_i_i_fu_541_p2.read() | p_39_demorgan_i_not_i_fu_551_p2.read());
}

void CvtColor::thread_brmerge_i_i_not_i_i2_fu_605_p2() {
    brmerge_i_i_not_i_i2_fu_605_p2 = (p_39_demorgan_i_i_i17_reg_816.read() & neg_src_not_i_i19_i_s_fu_600_p2.read());
}

void CvtColor::thread_brmerge_i_i_not_i_i_s_fu_546_p2() {
    brmerge_i_i_not_i_i_s_fu_546_p2 = (p_39_demorgan_i_i_i_i_reg_792.read() & neg_src_not_i_i_i_i_fu_541_p2.read());
}

void CvtColor::thread_carry_1_fu_479_p2() {
    carry_1_fu_479_p2 = (tmp_71_fu_452_p3.read() & tmp_24_i_i9_i_i_fu_473_p2.read());
}

void CvtColor::thread_carry_fu_375_p2() {
    carry_fu_375_p2 = (tmp_67_fu_348_p3.read() & tmp_24_i_i_i_i_fu_369_p2.read());
}

void CvtColor::thread_cols_1_fu_199_p1() {
    cols_1_fu_199_p1 = cols.read().range(9-1, 0);
}

void CvtColor::thread_deleted_zeros_1_fu_506_p3() {
    deleted_zeros_1_fu_506_p3 = (!carry_1_fu_479_p2.read()[0].is_01())? sc_lv<1>(): ((carry_1_fu_479_p2.read()[0].to_bool())? Range1_all_ones_1_fu_494_p2.read(): Range1_all_zeros_1_fu_500_p2.read());
}

void CvtColor::thread_deleted_zeros_fu_402_p3() {
    deleted_zeros_fu_402_p3 = (!carry_fu_375_p2.read()[0].is_01())? sc_lv<1>(): ((carry_fu_375_p2.read()[0].to_bool())? Range1_all_ones_fu_390_p2.read(): Range1_all_zeros_fu_396_p2.read());
}

void CvtColor::thread_exitcond1_i_fu_203_p2() {
    exitcond1_i_fu_203_p2 = (!i_i_reg_173.read().is_01() || !rows_1_fu_195_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_173.read() == rows_1_fu_195_p1.read());
}

void CvtColor::thread_exitcond_i_fu_214_p2() {
    exitcond_i_fu_214_p2 = (!j_i_reg_184.read().is_01() || !cols_1_fu_199_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(j_i_reg_184.read() == cols_1_fu_199_p1.read());
}

void CvtColor::thread_grp_fu_650_p0() {
    grp_fu_650_p0 =  (sc_lv<8>) (grp_fu_650_p00.read());
}

void CvtColor::thread_grp_fu_650_p00() {
    grp_fu_650_p00 = esl_zext<30,8>(ap_reg_pp0_iter2_tmp_77_reg_728.read());
}

void CvtColor::thread_grp_fu_650_p1() {
    grp_fu_650_p1 =  (sc_lv<23>) (ap_const_lv30_259168);
}

void CvtColor::thread_grp_fu_650_p2() {
    grp_fu_650_p2 =  (sc_lv<29>) (grp_fu_650_p20.read());
}

void CvtColor::thread_grp_fu_650_p20() {
    grp_fu_650_p20 = esl_zext<30,29>(grp_fu_660_p3.read());
}

void CvtColor::thread_grp_fu_660_p0() {
    grp_fu_660_p0 =  (sc_lv<8>) (grp_fu_660_p00.read());
}

void CvtColor::thread_grp_fu_660_p00() {
    grp_fu_660_p00 = esl_zext<28,8>(ap_reg_pp0_iter2_tmp_78_reg_733.read());
}

void CvtColor::thread_grp_fu_660_p1() {
    grp_fu_660_p1 =  (sc_lv<20>) (ap_const_lv28_74BC6);
}

void CvtColor::thread_grp_fu_668_p1() {
    grp_fu_668_p1 =  (sc_lv<23>) (ap_const_lv32_2DA1CA);
}

void CvtColor::thread_grp_fu_668_p2() {
    grp_fu_668_p2 =  (sc_lv<31>) (ap_const_lv32_20000000);
}

void CvtColor::thread_grp_fu_681_p1() {
    grp_fu_681_p1 =  (sc_lv<23>) (ap_const_lv32_241893);
}

void CvtColor::thread_grp_fu_681_p2() {
    grp_fu_681_p2 =  (sc_lv<31>) (ap_const_lv32_20000000);
}

void CvtColor::thread_i_fu_208_p2() {
    i_fu_208_p2 = (!i_i_reg_173.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_i_reg_173.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void CvtColor::thread_i_op_assign_3_i_fu_303_p2() {
    i_op_assign_3_i_fu_303_p2 = (!tmp_30_cast_i_i_fu_296_p1.read().is_01() || !tmp_31_cast_i_i_fu_299_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_30_cast_i_i_fu_296_p1.read()) - sc_biguint<9>(tmp_31_cast_i_i_fu_299_p1.read()));
}

void CvtColor::thread_i_op_assign_4_i_fu_312_p2() {
    i_op_assign_4_i_fu_312_p2 = (!tmp_33_cast_i_i_fu_309_p1.read().is_01() || !tmp_31_cast_i_i_fu_299_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_33_cast_i_i_fu_309_p1.read()) - sc_biguint<9>(tmp_31_cast_i_i_fu_299_p1.read()));
}

void CvtColor::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_i_fu_203_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void CvtColor::thread_j_fu_219_p2() {
    j_fu_219_p2 = (!j_i_reg_184.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(j_i_reg_184.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void CvtColor::thread_neg_src_4_fu_590_p2() {
    neg_src_4_fu_590_p2 = (signbit_1_reg_798.read() & tmp_25_i_i15_i_i_fu_585_p2.read());
}

void CvtColor::thread_neg_src_fu_531_p2() {
    neg_src_fu_531_p2 = (signbit_reg_774.read() & tmp_25_i_i_i_i_fu_526_p2.read());
}

void CvtColor::thread_neg_src_not_i_i19_i_s_fu_600_p2() {
    neg_src_not_i_i19_i_s_fu_600_p2 = (p_38_i_i_i14_i_i_reg_810.read() | signbit_not_i18_i_i_fu_595_p2.read());
}

void CvtColor::thread_neg_src_not_i_i_i_i_fu_541_p2() {
    neg_src_not_i_i_i_i_fu_541_p2 = (p_38_i_i_i_i_i_reg_786.read() | signbit_not_i_i_i_fu_536_p2.read());
}

void CvtColor::thread_not_carry_i_i_fu_282_p2() {
    not_carry_i_i_fu_282_p2 = (tmp_64_fu_268_p3.read() | p_Result_9_i_i_not_fu_276_p2.read());
}

void CvtColor::thread_p_38_i_i_i14_i_i_fu_514_p2() {
    p_38_i_i_i14_i_i_fu_514_p2 = (carry_1_fu_479_p2.read() & Range1_all_ones_1_fu_494_p2.read());
}

void CvtColor::thread_p_38_i_i_i_i_i_fu_410_p2() {
    p_38_i_i_i_i_i_fu_410_p2 = (carry_fu_375_p2.read() & Range1_all_ones_fu_390_p2.read());
}

void CvtColor::thread_p_39_demorgan_i_i_i17_fu_520_p2() {
    p_39_demorgan_i_i_i17_fu_520_p2 = (deleted_zeros_1_fu_506_p3.read() | signbit_1_fu_425_p3.read());
}

void CvtColor::thread_p_39_demorgan_i_i_i_i_fu_416_p2() {
    p_39_demorgan_i_i_i_i_fu_416_p2 = (deleted_zeros_fu_402_p3.read() | signbit_fu_321_p3.read());
}

void CvtColor::thread_p_39_demorgan_i_not_i_1_fu_610_p2() {
    p_39_demorgan_i_not_i_1_fu_610_p2 = (p_39_demorgan_i_i_i17_reg_816.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_p_39_demorgan_i_not_i_fu_551_p2() {
    p_39_demorgan_i_not_i_fu_551_p2 = (p_39_demorgan_i_i_i_i_reg_792.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_p_Result_9_i_i_not_fu_276_p2() {
    p_Result_9_i_i_not_fu_276_p2 = (tmp_63_fu_256_p3.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_p_Val2_13_fu_328_p4() {
    p_Val2_13_fu_328_p4 = grp_fu_668_p3.read().range(29, 22);
}

void CvtColor::thread_p_Val2_14_fu_355_p2() {
    p_Val2_14_fu_355_p2 = (!p_Val2_13_fu_328_p4.read().is_01() || !tmp_23_i_i_i_i_fu_344_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_13_fu_328_p4.read()) + sc_biguint<8>(tmp_23_i_i_i_i_fu_344_p1.read()));
}

void CvtColor::thread_p_Val2_18_fu_432_p4() {
    p_Val2_18_fu_432_p4 = grp_fu_681_p3.read().range(29, 22);
}

void CvtColor::thread_p_Val2_19_fu_459_p2() {
    p_Val2_19_fu_459_p2 = (!p_Val2_18_fu_432_p4.read().is_01() || !tmp_23_i_i5_i_i_fu_448_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_18_fu_432_p4.read()) + sc_biguint<8>(tmp_23_i_i5_i_i_fu_448_p1.read()));
}

void CvtColor::thread_p_Val2_9_fu_263_p2() {
    p_Val2_9_fu_263_p2 = (!p_Val2_8_reg_749.read().is_01() || !tmp_26_i_i_i_i_fu_253_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_8_reg_749.read()) + sc_biguint<8>(tmp_26_i_i_i_i_fu_253_p1.read()));
}

void CvtColor::thread_p_Val2_s_fu_288_p3() {
    p_Val2_s_fu_288_p3 = (!not_carry_i_i_fu_282_p2.read()[0].is_01())? sc_lv<8>(): ((not_carry_i_i_fu_282_p2.read()[0].to_bool())? p_Val2_9_fu_263_p2.read(): ap_const_lv8_FF);
}

void CvtColor::thread_p_i_i24_i_i_fu_628_p3() {
    p_i_i24_i_i_fu_628_p3 = (!neg_src_4_fu_590_p2.read()[0].is_01())? sc_lv<8>(): ((neg_src_4_fu_590_p2.read()[0].to_bool())? ap_const_lv8_0: p_Val2_19_reg_804.read());
}

void CvtColor::thread_p_i_i_i_i_fu_569_p3() {
    p_i_i_i_i_fu_569_p3 = (!neg_src_fu_531_p2.read()[0].is_01())? sc_lv<8>(): ((neg_src_fu_531_p2.read()[0].to_bool())? ap_const_lv8_0: p_Val2_14_reg_780.read());
}

void CvtColor::thread_p_mux_i_i1_i_i_fu_562_p3() {
    p_mux_i_i1_i_i_fu_562_p3 = (!brmerge_i_i_not_i_i_s_fu_546_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_i_i_not_i_i_s_fu_546_p2.read()[0].to_bool())? p_Val2_14_reg_780.read(): ap_const_lv8_FF);
}

void CvtColor::thread_p_mux_i_i23_i_i_fu_621_p3() {
    p_mux_i_i23_i_i_fu_621_p3 = (!brmerge_i_i_not_i_i2_fu_605_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_i_i_not_i_i2_fu_605_p2.read()[0].to_bool())? p_Val2_19_reg_804.read(): ap_const_lv8_FF);
}

void CvtColor::thread_r_V_4_i_i_fu_644_p0() {
    r_V_4_i_i_fu_644_p0 =  (sc_lv<8>) (r_V_4_i_i_fu_644_p00.read());
}

void CvtColor::thread_r_V_4_i_i_fu_644_p00() {
    r_V_4_i_i_fu_644_p00 = esl_zext<29,8>(tmp_76_reg_722.read());
}

void CvtColor::thread_r_V_4_i_i_fu_644_p1() {
    r_V_4_i_i_fu_644_p1 =  (sc_lv<22>) (ap_const_lv29_1322D0);
}

void CvtColor::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void CvtColor::thread_rows_1_fu_195_p1() {
    rows_1_fu_195_p1 = rows.read().range(10-1, 0);
}

void CvtColor::thread_signbit_1_fu_425_p3() {
    signbit_1_fu_425_p3 = grp_fu_681_p3.read().range(31, 31);
}

void CvtColor::thread_signbit_fu_321_p3() {
    signbit_fu_321_p3 = grp_fu_668_p3.read().range(31, 31);
}

void CvtColor::thread_signbit_not_i18_i_i_fu_595_p2() {
    signbit_not_i18_i_i_fu_595_p2 = (signbit_1_reg_798.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_signbit_not_i_i_i_fu_536_p2() {
    signbit_not_i_i_i_fu_536_p2 = (signbit_reg_774.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_src_mat_data_stream_1_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0))) {
        src_mat_data_stream_1_blk_n = src_mat_data_stream_1_empty_n.read();
    } else {
        src_mat_data_stream_1_blk_n = ap_const_logic_1;
    }
}

void CvtColor::thread_src_mat_data_stream_1_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        src_mat_data_stream_1_read = ap_const_logic_1;
    } else {
        src_mat_data_stream_1_read = ap_const_logic_0;
    }
}

void CvtColor::thread_src_mat_data_stream_2_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0))) {
        src_mat_data_stream_2_blk_n = src_mat_data_stream_2_empty_n.read();
    } else {
        src_mat_data_stream_2_blk_n = ap_const_logic_1;
    }
}

void CvtColor::thread_src_mat_data_stream_2_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        src_mat_data_stream_2_read = ap_const_logic_1;
    } else {
        src_mat_data_stream_2_read = ap_const_logic_0;
    }
}

void CvtColor::thread_src_mat_data_stream_s_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0))) {
        src_mat_data_stream_s_blk_n = src_mat_data_stream_s_empty_n.read();
    } else {
        src_mat_data_stream_s_blk_n = ap_const_logic_1;
    }
}

void CvtColor::thread_src_mat_data_stream_s_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_713.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        src_mat_data_stream_s_read = ap_const_logic_1;
    } else {
        src_mat_data_stream_s_read = ap_const_logic_0;
    }
}

void CvtColor::thread_start_out() {
    start_out = real_start.read();
}

void CvtColor::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void CvtColor::thread_tmp_23_i_i5_i_i_fu_448_p1() {
    tmp_23_i_i5_i_i_fu_448_p1 = esl_zext<8,1>(tmp_70_fu_441_p3.read());
}

void CvtColor::thread_tmp_23_i_i_i_i_fu_344_p1() {
    tmp_23_i_i_i_i_fu_344_p1 = esl_zext<8,1>(tmp_66_fu_337_p3.read());
}

void CvtColor::thread_tmp_24_i_i9_i_i_fu_473_p2() {
    tmp_24_i_i9_i_i_fu_473_p2 = (tmp_72_fu_465_p3.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_tmp_24_i_i_i_i_fu_369_p2() {
    tmp_24_i_i_i_i_fu_369_p2 = (tmp_68_fu_361_p3.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_tmp_25_i_i15_i_i_fu_585_p2() {
    tmp_25_i_i15_i_i_fu_585_p2 = (p_38_i_i_i14_i_i_reg_810.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_tmp_25_i_i_i_i_fu_526_p2() {
    tmp_25_i_i_i_i_fu_526_p2 = (p_38_i_i_i_i_i_reg_786.read() ^ ap_const_lv1_1);
}

void CvtColor::thread_tmp_26_i_i_i_i_fu_253_p1() {
    tmp_26_i_i_i_i_fu_253_p1 = esl_zext<8,1>(tmp_reg_754.read());
}

void CvtColor::thread_tmp_30_cast_i_i_fu_296_p1() {
    tmp_30_cast_i_i_fu_296_p1 = esl_zext<9,8>(ap_reg_pp0_iter3_tmp_76_reg_722.read());
}

void CvtColor::thread_tmp_31_cast_i_i_fu_299_p1() {
    tmp_31_cast_i_i_fu_299_p1 = esl_zext<9,8>(p_Val2_s_fu_288_p3.read());
}

void CvtColor::thread_tmp_33_cast_i_i_fu_309_p1() {
    tmp_33_cast_i_i_fu_309_p1 = esl_zext<9,8>(ap_reg_pp0_iter3_tmp_78_reg_733.read());
}

void CvtColor::thread_tmp_45_i_fu_485_p4() {
    tmp_45_i_fu_485_p4 = grp_fu_681_p3.read().range(31, 30);
}

void CvtColor::thread_tmp_63_fu_256_p3() {
    tmp_63_fu_256_p3 = r_V_1_reg_744.read().range(29, 29);
}

void CvtColor::thread_tmp_64_fu_268_p3() {
    tmp_64_fu_268_p3 = p_Val2_9_fu_263_p2.read().range(7, 7);
}

void CvtColor::thread_tmp_66_fu_337_p3() {
    tmp_66_fu_337_p3 = grp_fu_668_p3.read().range(21, 21);
}

void CvtColor::thread_tmp_67_fu_348_p3() {
    tmp_67_fu_348_p3 = grp_fu_668_p3.read().range(29, 29);
}

void CvtColor::thread_tmp_68_fu_361_p3() {
    tmp_68_fu_361_p3 = p_Val2_14_fu_355_p2.read().range(7, 7);
}

void CvtColor::thread_tmp_70_fu_441_p3() {
    tmp_70_fu_441_p3 = grp_fu_681_p3.read().range(21, 21);
}

void CvtColor::thread_tmp_71_fu_452_p3() {
    tmp_71_fu_452_p3 = grp_fu_681_p3.read().range(29, 29);
}

void CvtColor::thread_tmp_72_fu_465_p3() {
    tmp_72_fu_465_p3 = p_Val2_19_fu_459_p2.read().range(7, 7);
}

void CvtColor::thread_tmp_i_125_fu_381_p4() {
    tmp_i_125_fu_381_p4 = grp_fu_668_p3.read().range(31, 30);
}

void CvtColor::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_i_fu_203_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_i_fu_214_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(exitcond_i_fu_214_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

