// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module YCrCb_GUASSIAN_Block_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        nor_copy1_rows_V_out_din,
        nor_copy1_rows_V_out_full_n,
        nor_copy1_rows_V_out_write,
        nor_copy1_cols_V_out_din,
        nor_copy1_cols_V_out_full_n,
        nor_copy1_cols_V_out_write,
        Sim_rows_V_out_din,
        Sim_rows_V_out_full_n,
        Sim_rows_V_out_write,
        Sim_cols_V_out_din,
        Sim_cols_V_out_full_n,
        Sim_cols_V_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [10:0] nor_copy1_rows_V_out_din;
input   nor_copy1_rows_V_out_full_n;
output   nor_copy1_rows_V_out_write;
output  [9:0] nor_copy1_cols_V_out_din;
input   nor_copy1_cols_V_out_full_n;
output   nor_copy1_cols_V_out_write;
output  [10:0] Sim_rows_V_out_din;
input   Sim_rows_V_out_full_n;
output   Sim_rows_V_out_write;
output  [9:0] Sim_cols_V_out_din;
input   Sim_cols_V_out_full_n;
output   Sim_cols_V_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg nor_copy1_rows_V_out_write;
reg nor_copy1_cols_V_out_write;
reg Sim_rows_V_out_write;
reg Sim_cols_V_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    nor_copy1_rows_V_out_blk_n;
reg    nor_copy1_cols_V_out_blk_n;
reg    Sim_rows_V_out_blk_n;
reg    Sim_cols_V_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (1'b0 == Sim_cols_V_out_full_n) | (1'b0 == Sim_rows_V_out_full_n) | (nor_copy1_cols_V_out_full_n == 1'b0) | (nor_copy1_rows_V_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Sim_cols_V_out_blk_n = Sim_cols_V_out_full_n;
    end else begin
        Sim_cols_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == Sim_cols_V_out_full_n) | (1'b0 == Sim_rows_V_out_full_n) | (nor_copy1_cols_V_out_full_n == 1'b0) | (nor_copy1_rows_V_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Sim_cols_V_out_write = 1'b1;
    end else begin
        Sim_cols_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Sim_rows_V_out_blk_n = Sim_rows_V_out_full_n;
    end else begin
        Sim_rows_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == Sim_cols_V_out_full_n) | (1'b0 == Sim_rows_V_out_full_n) | (nor_copy1_cols_V_out_full_n == 1'b0) | (nor_copy1_rows_V_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Sim_rows_V_out_write = 1'b1;
    end else begin
        Sim_rows_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == Sim_cols_V_out_full_n) | (1'b0 == Sim_rows_V_out_full_n) | (nor_copy1_cols_V_out_full_n == 1'b0) | (nor_copy1_rows_V_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == Sim_cols_V_out_full_n) | (1'b0 == Sim_rows_V_out_full_n) | (nor_copy1_cols_V_out_full_n == 1'b0) | (nor_copy1_rows_V_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        nor_copy1_cols_V_out_blk_n = nor_copy1_cols_V_out_full_n;
    end else begin
        nor_copy1_cols_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == Sim_cols_V_out_full_n) | (1'b0 == Sim_rows_V_out_full_n) | (nor_copy1_cols_V_out_full_n == 1'b0) | (nor_copy1_rows_V_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        nor_copy1_cols_V_out_write = 1'b1;
    end else begin
        nor_copy1_cols_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        nor_copy1_rows_V_out_blk_n = nor_copy1_rows_V_out_full_n;
    end else begin
        nor_copy1_rows_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == Sim_cols_V_out_full_n) | (1'b0 == Sim_rows_V_out_full_n) | (nor_copy1_cols_V_out_full_n == 1'b0) | (nor_copy1_rows_V_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        nor_copy1_rows_V_out_write = 1'b1;
    end else begin
        nor_copy1_rows_V_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Sim_cols_V_out_din = 10'd480;

assign Sim_rows_V_out_din = 11'd720;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (1'b0 == Sim_cols_V_out_full_n) | (1'b0 == Sim_rows_V_out_full_n) | (nor_copy1_cols_V_out_full_n == 1'b0) | (nor_copy1_rows_V_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign nor_copy1_cols_V_out_din = 10'd480;

assign nor_copy1_rows_V_out_din = 11'd720;

endmodule //YCrCb_GUASSIAN_Block_2
