// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module YCrCb_GUASSIAN (
        rows,
        cols,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        src_data_stream_2_V_dout,
        src_data_stream_2_V_empty_n,
        src_data_stream_2_V_read,
        res_data_stream_V_din,
        res_data_stream_V_full_n,
        res_data_stream_V_write,
        nor_data_stream_V_din,
        nor_data_stream_V_full_n,
        nor_data_stream_V_write,
        threshold,
        ap_clk,
        ap_rst,
        ap_start,
        rows_ap_vld,
        cols_ap_vld,
        ap_done,
        threshold_ap_vld,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] rows;
input  [31:0] cols;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
input  [7:0] src_data_stream_2_V_dout;
input   src_data_stream_2_V_empty_n;
output   src_data_stream_2_V_read;
output  [7:0] res_data_stream_V_din;
input   res_data_stream_V_full_n;
output   res_data_stream_V_write;
output  [31:0] nor_data_stream_V_din;
input   nor_data_stream_V_full_n;
output   nor_data_stream_V_write;
output  [63:0] threshold;
input   ap_clk;
input   ap_rst;
input   ap_start;
input   rows_ap_vld;
input   cols_ap_vld;
output   ap_done;
output   threshold_ap_vld;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    YCrCb_GUASSIAN_Block_2_U0_ap_start;
wire    YCrCb_GUASSIAN_Block_2_U0_ap_done;
wire    YCrCb_GUASSIAN_Block_2_U0_ap_continue;
wire    YCrCb_GUASSIAN_Block_2_U0_ap_idle;
wire    YCrCb_GUASSIAN_Block_2_U0_ap_ready;
wire   [10:0] YCrCb_GUASSIAN_Block_2_U0_nor_copy1_rows_V_out_din;
wire    YCrCb_GUASSIAN_Block_2_U0_nor_copy1_rows_V_out_write;
wire   [9:0] YCrCb_GUASSIAN_Block_2_U0_nor_copy1_cols_V_out_din;
wire    YCrCb_GUASSIAN_Block_2_U0_nor_copy1_cols_V_out_write;
wire   [10:0] YCrCb_GUASSIAN_Block_2_U0_Sim_rows_V_out_din;
wire    YCrCb_GUASSIAN_Block_2_U0_Sim_rows_V_out_write;
wire   [9:0] YCrCb_GUASSIAN_Block_2_U0_Sim_cols_V_out_din;
wire    YCrCb_GUASSIAN_Block_2_U0_Sim_cols_V_out_write;
wire    CvtColor_U0_ap_start;
wire    CvtColor_U0_ap_done;
wire    CvtColor_U0_ap_continue;
wire    CvtColor_U0_ap_idle;
wire    CvtColor_U0_ap_ready;
wire    CvtColor_U0_start_out;
wire    CvtColor_U0_start_write;
wire    CvtColor_U0_src_mat_data_stream_s_read;
wire    CvtColor_U0_src_mat_data_stream_1_read;
wire    CvtColor_U0_src_mat_data_stream_2_read;
wire   [7:0] CvtColor_U0_YCrCb_IMG_data_strea_i_din;
wire    CvtColor_U0_YCrCb_IMG_data_strea_i_write;
wire   [7:0] CvtColor_U0_YCrCb_IMG_data_strea_1_i_din;
wire    CvtColor_U0_YCrCb_IMG_data_strea_1_i_write;
wire   [7:0] CvtColor_U0_YCrCb_IMG_data_strea_2_i_din;
wire    CvtColor_U0_YCrCb_IMG_data_strea_2_i_write;
wire    Split_U0_ap_start;
wire    Split_U0_ap_done;
wire    Split_U0_ap_continue;
wire    Split_U0_ap_idle;
wire    Split_U0_ap_ready;
wire    Split_U0_start_out;
wire    Split_U0_start_write;
wire    Split_U0_src_data_stream_0_V_read;
wire    Split_U0_src_data_stream_1_V_read;
wire    Split_U0_src_data_stream_2_V_read;
wire   [7:0] Split_U0_dst0_data_stream_V;
wire    Split_U0_dst0_data_stream_V_ap_vld;
wire   [7:0] Split_U0_dst1_data_stream_V_din;
wire    Split_U0_dst1_data_stream_V_write;
wire   [7:0] Split_U0_dst2_data_stream_V_din;
wire    Split_U0_dst2_data_stream_V_write;
wire    YCrCb_GUASSIAN_Loop_1_U0_ap_start;
wire    YCrCb_GUASSIAN_Loop_1_U0_ap_done;
wire    YCrCb_GUASSIAN_Loop_1_U0_ap_continue;
wire    YCrCb_GUASSIAN_Loop_1_U0_ap_idle;
wire    YCrCb_GUASSIAN_Loop_1_U0_ap_ready;
wire    YCrCb_GUASSIAN_Loop_1_U0_start_out;
wire    YCrCb_GUASSIAN_Loop_1_U0_start_write;
wire    YCrCb_GUASSIAN_Loop_1_U0_Cr_Img_data_stream_0_V_read;
wire    YCrCb_GUASSIAN_Loop_1_U0_Cb_Img_data_stream_0_V_read;
wire   [31:0] YCrCb_GUASSIAN_Loop_1_U0_Sim_data_stream_0_V_din;
wire    YCrCb_GUASSIAN_Loop_1_U0_Sim_data_stream_0_V_write;
wire    Duplicate349_U0_ap_start;
wire    Duplicate349_U0_start_full_n;
wire    Duplicate349_U0_ap_done;
wire    Duplicate349_U0_ap_continue;
wire    Duplicate349_U0_ap_idle;
wire    Duplicate349_U0_ap_ready;
wire    Duplicate349_U0_start_out;
wire    Duplicate349_U0_start_write;
wire    Duplicate349_U0_src_rows_V_read;
wire    Duplicate349_U0_src_cols_V_read;
wire    Duplicate349_U0_src_data_stream_V_read;
wire   [31:0] Duplicate349_U0_dst1_data_stream_V_din;
wire    Duplicate349_U0_dst1_data_stream_V_write;
wire   [31:0] Duplicate349_U0_dst2_data_stream_V_din;
wire    Duplicate349_U0_dst2_data_stream_V_write;
wire    MinMaxLoc_U0_ap_start;
wire    MinMaxLoc_U0_ap_done;
wire    MinMaxLoc_U0_ap_continue;
wire    MinMaxLoc_U0_ap_idle;
wire    MinMaxLoc_U0_ap_ready;
wire    MinMaxLoc_U0_src_data_stream_V_read;
wire   [63:0] MinMaxLoc_U0_min_val_out_din;
wire    MinMaxLoc_U0_min_val_out_write;
wire   [63:0] MinMaxLoc_U0_max_val_out_din;
wire    MinMaxLoc_U0_max_val_out_write;
wire    normalized_U0_ap_start;
wire    normalized_U0_start_full_n;
wire    normalized_U0_start_out;
wire    normalized_U0_start_write;
wire    normalized_U0_sim_data_stream_V_read;
wire   [31:0] normalized_U0_nor_data_stream_V_din;
wire    normalized_U0_nor_data_stream_V_write;
wire   [7:0] normalized_U0_gray_data_stream_V_din;
wire    normalized_U0_gray_data_stream_V_write;
wire    normalized_U0_max_read;
wire    normalized_U0_min_read;
wire    normalized_U0_ap_done;
wire    normalized_U0_ap_ready;
wire    normalized_U0_ap_idle;
wire    normalized_U0_ap_continue;
wire    Duplicate_U0_ap_start;
wire    Duplicate_U0_ap_done;
wire    Duplicate_U0_ap_continue;
wire    Duplicate_U0_ap_idle;
wire    Duplicate_U0_ap_ready;
wire    Duplicate_U0_start_out;
wire    Duplicate_U0_start_write;
wire    Duplicate_U0_src_rows_V_read;
wire    Duplicate_U0_src_cols_V_read;
wire    Duplicate_U0_src_data_stream_V_read;
wire   [31:0] Duplicate_U0_dst1_data_stream_V_din;
wire    Duplicate_U0_dst1_data_stream_V_write;
wire   [31:0] Duplicate_U0_dst2_data_stream_V_din;
wire    Duplicate_U0_dst2_data_stream_V_write;
wire    ap_sync_continue;
wire    otsu_threshold_U0_ap_start;
wire    otsu_threshold_U0_ap_done;
wire    otsu_threshold_U0_ap_continue;
wire    otsu_threshold_U0_ap_idle;
wire    otsu_threshold_U0_ap_ready;
wire    otsu_threshold_U0_start_out;
wire    otsu_threshold_U0_start_write;
wire    otsu_threshold_U0_gray_data_stream_V_read;
wire   [63:0] otsu_threshold_U0_ret_out_din;
wire    otsu_threshold_U0_ret_out_write;
wire   [63:0] otsu_threshold_U0_ret_out1_din;
wire    otsu_threshold_U0_ret_out1_write;
wire    YCrCb_GUASSIAN_Block_U0_ap_start;
wire    YCrCb_GUASSIAN_Block_U0_ap_done;
wire    YCrCb_GUASSIAN_Block_U0_ap_continue;
wire    YCrCb_GUASSIAN_Block_U0_ap_idle;
wire    YCrCb_GUASSIAN_Block_U0_ap_ready;
wire    YCrCb_GUASSIAN_Block_U0_tmp3_read;
wire   [63:0] YCrCb_GUASSIAN_Block_U0_threshold;
wire    YCrCb_GUASSIAN_Block_U0_threshold_ap_vld;
wire    YCrCb_GUASSIAN_Loop_U0_ap_start;
wire    YCrCb_GUASSIAN_Loop_U0_ap_done;
wire    YCrCb_GUASSIAN_Loop_U0_ap_continue;
wire    YCrCb_GUASSIAN_Loop_U0_ap_idle;
wire    YCrCb_GUASSIAN_Loop_U0_ap_ready;
wire    YCrCb_GUASSIAN_Loop_U0_start_out;
wire    YCrCb_GUASSIAN_Loop_U0_start_write;
wire    YCrCb_GUASSIAN_Loop_U0_nor_copy2_data_stream_0_V_read;
wire    YCrCb_GUASSIAN_Loop_U0_tmp3_read;
wire   [7:0] YCrCb_GUASSIAN_Loop_U0_origin_data_stream_0_V_din;
wire    YCrCb_GUASSIAN_Loop_U0_origin_data_stream_0_V_write;
wire    erode_dilate_U0_img_data_stream_V_read;
wire   [7:0] erode_dilate_U0_res_data_stream_V_din;
wire    erode_dilate_U0_res_data_stream_V_write;
wire    erode_dilate_U0_ap_done;
wire    erode_dilate_U0_ap_start;
wire    erode_dilate_U0_ap_ready;
wire    erode_dilate_U0_ap_idle;
wire    erode_dilate_U0_ap_continue;
wire    nor_copy1_rows_V_c_i_full_n;
wire   [10:0] nor_copy1_rows_V_c_i_dout;
wire    nor_copy1_rows_V_c_i_empty_n;
wire    nor_copy1_cols_V_c_i_full_n;
wire   [9:0] nor_copy1_cols_V_c_i_dout;
wire    nor_copy1_cols_V_c_i_empty_n;
wire    Sim_rows_V_c_i_full_n;
wire   [10:0] Sim_rows_V_c_i_dout;
wire    Sim_rows_V_c_i_empty_n;
wire    Sim_cols_V_c_i_full_n;
wire   [9:0] Sim_cols_V_c_i_dout;
wire    Sim_cols_V_c_i_empty_n;
wire    YCrCb_IMG_data_strea_full_n;
wire   [7:0] YCrCb_IMG_data_strea_dout;
wire    YCrCb_IMG_data_strea_empty_n;
wire    YCrCb_IMG_data_strea_1_full_n;
wire   [7:0] YCrCb_IMG_data_strea_1_dout;
wire    YCrCb_IMG_data_strea_1_empty_n;
wire    YCrCb_IMG_data_strea_2_full_n;
wire   [7:0] YCrCb_IMG_data_strea_2_dout;
wire    YCrCb_IMG_data_strea_2_empty_n;
wire    Cr_Img_data_stream_0_full_n;
wire   [7:0] Cr_Img_data_stream_0_dout;
wire    Cr_Img_data_stream_0_empty_n;
wire    Cb_Img_data_stream_0_full_n;
wire   [7:0] Cb_Img_data_stream_0_dout;
wire    Cb_Img_data_stream_0_empty_n;
wire    Sim_data_stream_0_V_full_n;
wire   [31:0] Sim_data_stream_0_V_dout;
wire    Sim_data_stream_0_V_empty_n;
wire    Sim_copy1_data_strea_full_n;
wire   [31:0] Sim_copy1_data_strea_dout;
wire    Sim_copy1_data_strea_empty_n;
wire    Sim_copy2_data_strea_full_n;
wire   [31:0] Sim_copy2_data_strea_dout;
wire    Sim_copy2_data_strea_empty_n;
wire    min_c_i_full_n;
wire   [63:0] min_c_i_dout;
wire    min_c_i_empty_n;
wire    max_c_i_full_n;
wire   [63:0] max_c_i_dout;
wire    max_c_i_empty_n;
wire    nor_copy1_data_strea_full_n;
wire   [31:0] nor_copy1_data_strea_dout;
wire    nor_copy1_data_strea_empty_n;
wire    gray_data_stream_0_s_full_n;
wire   [7:0] gray_data_stream_0_s_dout;
wire    gray_data_stream_0_s_empty_n;
wire    nor_copy2_data_strea_full_n;
wire   [31:0] nor_copy2_data_strea_dout;
wire    nor_copy2_data_strea_empty_n;
wire    tmp3_c_i_full_n;
wire   [63:0] tmp3_c_i_dout;
wire    tmp3_c_i_empty_n;
wire    tmp3_c5_i_full_n;
wire   [63:0] tmp3_c5_i_dout;
wire    tmp3_c5_i_empty_n;
wire    origin_data_stream_0_full_n;
wire   [7:0] origin_data_stream_0_dout;
wire    origin_data_stream_0_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    YCrCb_GUASSIAN_Block_2_U0_start_full_n;
wire    YCrCb_GUASSIAN_Block_2_U0_start_write;
wire   [0:0] start_for_Split_U0_din;
wire    start_for_Split_U0_full_n;
wire   [0:0] start_for_Split_U0_dout;
wire    start_for_Split_U0_empty_n;
wire   [0:0] start_for_YCrCb_GUASSIAN_Loop_1_U0_din;
wire    start_for_YCrCb_GUASSIAN_Loop_1_U0_full_n;
wire   [0:0] start_for_YCrCb_GUASSIAN_Loop_1_U0_dout;
wire    start_for_YCrCb_GUASSIAN_Loop_1_U0_empty_n;
wire   [0:0] start_for_Duplicate349_U0_din;
wire    start_for_Duplicate349_U0_full_n;
wire   [0:0] start_for_Duplicate349_U0_dout;
wire    start_for_Duplicate349_U0_empty_n;
wire   [0:0] start_for_MinMaxLoc_U0_din;
wire    start_for_MinMaxLoc_U0_full_n;
wire   [0:0] start_for_MinMaxLoc_U0_dout;
wire    start_for_MinMaxLoc_U0_empty_n;
wire   [0:0] start_for_normalized_U0_din;
wire    start_for_normalized_U0_full_n;
wire   [0:0] start_for_normalized_U0_dout;
wire    start_for_normalized_U0_empty_n;
wire    MinMaxLoc_U0_start_full_n;
wire    MinMaxLoc_U0_start_write;
wire   [0:0] start_for_Duplicate_U0_din;
wire    start_for_Duplicate_U0_full_n;
wire   [0:0] start_for_Duplicate_U0_dout;
wire    start_for_Duplicate_U0_empty_n;
wire   [0:0] start_for_otsu_threshold_U0_din;
wire    start_for_otsu_threshold_U0_full_n;
wire   [0:0] start_for_otsu_threshold_U0_dout;
wire    start_for_otsu_threshold_U0_empty_n;
wire   [0:0] start_for_YCrCb_GUASSIAN_Loop_U0_din;
wire    start_for_YCrCb_GUASSIAN_Loop_U0_full_n;
wire   [0:0] start_for_YCrCb_GUASSIAN_Loop_U0_dout;
wire    start_for_YCrCb_GUASSIAN_Loop_U0_empty_n;
wire   [0:0] start_for_YCrCb_GUASSIAN_Block_U0_din;
wire    start_for_YCrCb_GUASSIAN_Block_U0_full_n;
wire   [0:0] start_for_YCrCb_GUASSIAN_Block_U0_dout;
wire    start_for_YCrCb_GUASSIAN_Block_U0_empty_n;
wire    YCrCb_GUASSIAN_Block_U0_start_full_n;
wire    YCrCb_GUASSIAN_Block_U0_start_write;
wire   [0:0] start_for_erode_dilate_U0_din;
wire    start_for_erode_dilate_U0_full_n;
wire   [0:0] start_for_erode_dilate_U0_dout;
wire    start_for_erode_dilate_U0_empty_n;
wire    erode_dilate_U0_start_full_n;
wire    erode_dilate_U0_start_write;

YCrCb_GUASSIAN_Block_2 YCrCb_GUASSIAN_Block_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(YCrCb_GUASSIAN_Block_2_U0_ap_start),
    .ap_done(YCrCb_GUASSIAN_Block_2_U0_ap_done),
    .ap_continue(YCrCb_GUASSIAN_Block_2_U0_ap_continue),
    .ap_idle(YCrCb_GUASSIAN_Block_2_U0_ap_idle),
    .ap_ready(YCrCb_GUASSIAN_Block_2_U0_ap_ready),
    .nor_copy1_rows_V_out_din(YCrCb_GUASSIAN_Block_2_U0_nor_copy1_rows_V_out_din),
    .nor_copy1_rows_V_out_full_n(nor_copy1_rows_V_c_i_full_n),
    .nor_copy1_rows_V_out_write(YCrCb_GUASSIAN_Block_2_U0_nor_copy1_rows_V_out_write),
    .nor_copy1_cols_V_out_din(YCrCb_GUASSIAN_Block_2_U0_nor_copy1_cols_V_out_din),
    .nor_copy1_cols_V_out_full_n(nor_copy1_cols_V_c_i_full_n),
    .nor_copy1_cols_V_out_write(YCrCb_GUASSIAN_Block_2_U0_nor_copy1_cols_V_out_write),
    .Sim_rows_V_out_din(YCrCb_GUASSIAN_Block_2_U0_Sim_rows_V_out_din),
    .Sim_rows_V_out_full_n(Sim_rows_V_c_i_full_n),
    .Sim_rows_V_out_write(YCrCb_GUASSIAN_Block_2_U0_Sim_rows_V_out_write),
    .Sim_cols_V_out_din(YCrCb_GUASSIAN_Block_2_U0_Sim_cols_V_out_din),
    .Sim_cols_V_out_full_n(Sim_cols_V_c_i_full_n),
    .Sim_cols_V_out_write(YCrCb_GUASSIAN_Block_2_U0_Sim_cols_V_out_write)
);

CvtColor CvtColor_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(CvtColor_U0_ap_start),
    .start_full_n(start_for_Split_U0_full_n),
    .ap_done(CvtColor_U0_ap_done),
    .ap_continue(CvtColor_U0_ap_continue),
    .ap_idle(CvtColor_U0_ap_idle),
    .ap_ready(CvtColor_U0_ap_ready),
    .start_out(CvtColor_U0_start_out),
    .start_write(CvtColor_U0_start_write),
    .rows(rows),
    .cols(cols),
    .src_mat_data_stream_s_dout(src_data_stream_0_V_dout),
    .src_mat_data_stream_s_empty_n(src_data_stream_0_V_empty_n),
    .src_mat_data_stream_s_read(CvtColor_U0_src_mat_data_stream_s_read),
    .src_mat_data_stream_1_dout(src_data_stream_1_V_dout),
    .src_mat_data_stream_1_empty_n(src_data_stream_1_V_empty_n),
    .src_mat_data_stream_1_read(CvtColor_U0_src_mat_data_stream_1_read),
    .src_mat_data_stream_2_dout(src_data_stream_2_V_dout),
    .src_mat_data_stream_2_empty_n(src_data_stream_2_V_empty_n),
    .src_mat_data_stream_2_read(CvtColor_U0_src_mat_data_stream_2_read),
    .YCrCb_IMG_data_strea_i_din(CvtColor_U0_YCrCb_IMG_data_strea_i_din),
    .YCrCb_IMG_data_strea_i_full_n(YCrCb_IMG_data_strea_full_n),
    .YCrCb_IMG_data_strea_i_write(CvtColor_U0_YCrCb_IMG_data_strea_i_write),
    .YCrCb_IMG_data_strea_1_i_din(CvtColor_U0_YCrCb_IMG_data_strea_1_i_din),
    .YCrCb_IMG_data_strea_1_i_full_n(YCrCb_IMG_data_strea_1_full_n),
    .YCrCb_IMG_data_strea_1_i_write(CvtColor_U0_YCrCb_IMG_data_strea_1_i_write),
    .YCrCb_IMG_data_strea_2_i_din(CvtColor_U0_YCrCb_IMG_data_strea_2_i_din),
    .YCrCb_IMG_data_strea_2_i_full_n(YCrCb_IMG_data_strea_2_full_n),
    .YCrCb_IMG_data_strea_2_i_write(CvtColor_U0_YCrCb_IMG_data_strea_2_i_write)
);

Split Split_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Split_U0_ap_start),
    .start_full_n(start_for_YCrCb_GUASSIAN_Loop_1_U0_full_n),
    .ap_done(Split_U0_ap_done),
    .ap_continue(Split_U0_ap_continue),
    .ap_idle(Split_U0_ap_idle),
    .ap_ready(Split_U0_ap_ready),
    .start_out(Split_U0_start_out),
    .start_write(Split_U0_start_write),
    .src_data_stream_0_V_dout(YCrCb_IMG_data_strea_dout),
    .src_data_stream_0_V_empty_n(YCrCb_IMG_data_strea_empty_n),
    .src_data_stream_0_V_read(Split_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(YCrCb_IMG_data_strea_1_dout),
    .src_data_stream_1_V_empty_n(YCrCb_IMG_data_strea_1_empty_n),
    .src_data_stream_1_V_read(Split_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(YCrCb_IMG_data_strea_2_dout),
    .src_data_stream_2_V_empty_n(YCrCb_IMG_data_strea_2_empty_n),
    .src_data_stream_2_V_read(Split_U0_src_data_stream_2_V_read),
    .dst0_data_stream_V(Split_U0_dst0_data_stream_V),
    .dst0_data_stream_V_ap_vld(Split_U0_dst0_data_stream_V_ap_vld),
    .dst1_data_stream_V_din(Split_U0_dst1_data_stream_V_din),
    .dst1_data_stream_V_full_n(Cr_Img_data_stream_0_full_n),
    .dst1_data_stream_V_write(Split_U0_dst1_data_stream_V_write),
    .dst2_data_stream_V_din(Split_U0_dst2_data_stream_V_din),
    .dst2_data_stream_V_full_n(Cb_Img_data_stream_0_full_n),
    .dst2_data_stream_V_write(Split_U0_dst2_data_stream_V_write)
);

YCrCb_GUASSIAN_Loop_1 YCrCb_GUASSIAN_Loop_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(YCrCb_GUASSIAN_Loop_1_U0_ap_start),
    .start_full_n(start_for_Duplicate349_U0_full_n),
    .ap_done(YCrCb_GUASSIAN_Loop_1_U0_ap_done),
    .ap_continue(YCrCb_GUASSIAN_Loop_1_U0_ap_continue),
    .ap_idle(YCrCb_GUASSIAN_Loop_1_U0_ap_idle),
    .ap_ready(YCrCb_GUASSIAN_Loop_1_U0_ap_ready),
    .start_out(YCrCb_GUASSIAN_Loop_1_U0_start_out),
    .start_write(YCrCb_GUASSIAN_Loop_1_U0_start_write),
    .Cr_Img_data_stream_0_V_dout(Cr_Img_data_stream_0_dout),
    .Cr_Img_data_stream_0_V_empty_n(Cr_Img_data_stream_0_empty_n),
    .Cr_Img_data_stream_0_V_read(YCrCb_GUASSIAN_Loop_1_U0_Cr_Img_data_stream_0_V_read),
    .Cb_Img_data_stream_0_V_dout(Cb_Img_data_stream_0_dout),
    .Cb_Img_data_stream_0_V_empty_n(Cb_Img_data_stream_0_empty_n),
    .Cb_Img_data_stream_0_V_read(YCrCb_GUASSIAN_Loop_1_U0_Cb_Img_data_stream_0_V_read),
    .Sim_data_stream_0_V_din(YCrCb_GUASSIAN_Loop_1_U0_Sim_data_stream_0_V_din),
    .Sim_data_stream_0_V_full_n(Sim_data_stream_0_V_full_n),
    .Sim_data_stream_0_V_write(YCrCb_GUASSIAN_Loop_1_U0_Sim_data_stream_0_V_write)
);

Duplicate349 Duplicate349_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Duplicate349_U0_ap_start),
    .start_full_n(Duplicate349_U0_start_full_n),
    .ap_done(Duplicate349_U0_ap_done),
    .ap_continue(Duplicate349_U0_ap_continue),
    .ap_idle(Duplicate349_U0_ap_idle),
    .ap_ready(Duplicate349_U0_ap_ready),
    .start_out(Duplicate349_U0_start_out),
    .start_write(Duplicate349_U0_start_write),
    .src_rows_V_dout(Sim_rows_V_c_i_dout),
    .src_rows_V_empty_n(Sim_rows_V_c_i_empty_n),
    .src_rows_V_read(Duplicate349_U0_src_rows_V_read),
    .src_cols_V_dout(Sim_cols_V_c_i_dout),
    .src_cols_V_empty_n(Sim_cols_V_c_i_empty_n),
    .src_cols_V_read(Duplicate349_U0_src_cols_V_read),
    .src_data_stream_V_dout(Sim_data_stream_0_V_dout),
    .src_data_stream_V_empty_n(Sim_data_stream_0_V_empty_n),
    .src_data_stream_V_read(Duplicate349_U0_src_data_stream_V_read),
    .dst1_data_stream_V_din(Duplicate349_U0_dst1_data_stream_V_din),
    .dst1_data_stream_V_full_n(Sim_copy1_data_strea_full_n),
    .dst1_data_stream_V_write(Duplicate349_U0_dst1_data_stream_V_write),
    .dst2_data_stream_V_din(Duplicate349_U0_dst2_data_stream_V_din),
    .dst2_data_stream_V_full_n(Sim_copy2_data_strea_full_n),
    .dst2_data_stream_V_write(Duplicate349_U0_dst2_data_stream_V_write)
);

MinMaxLoc MinMaxLoc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MinMaxLoc_U0_ap_start),
    .ap_done(MinMaxLoc_U0_ap_done),
    .ap_continue(MinMaxLoc_U0_ap_continue),
    .ap_idle(MinMaxLoc_U0_ap_idle),
    .ap_ready(MinMaxLoc_U0_ap_ready),
    .src_data_stream_V_dout(Sim_copy1_data_strea_dout),
    .src_data_stream_V_empty_n(Sim_copy1_data_strea_empty_n),
    .src_data_stream_V_read(MinMaxLoc_U0_src_data_stream_V_read),
    .min_val_out_din(MinMaxLoc_U0_min_val_out_din),
    .min_val_out_full_n(min_c_i_full_n),
    .min_val_out_write(MinMaxLoc_U0_min_val_out_write),
    .max_val_out_din(MinMaxLoc_U0_max_val_out_din),
    .max_val_out_full_n(max_c_i_full_n),
    .max_val_out_write(MinMaxLoc_U0_max_val_out_write)
);

normalized normalized_U0(
    .ap_start(normalized_U0_ap_start),
    .start_full_n(normalized_U0_start_full_n),
    .start_out(normalized_U0_start_out),
    .start_write(normalized_U0_start_write),
    .sim_data_stream_V_dout(Sim_copy2_data_strea_dout),
    .sim_data_stream_V_empty_n(Sim_copy2_data_strea_empty_n),
    .sim_data_stream_V_read(normalized_U0_sim_data_stream_V_read),
    .nor_data_stream_V_din(normalized_U0_nor_data_stream_V_din),
    .nor_data_stream_V_full_n(nor_copy1_data_strea_full_n),
    .nor_data_stream_V_write(normalized_U0_nor_data_stream_V_write),
    .gray_data_stream_V_din(normalized_U0_gray_data_stream_V_din),
    .gray_data_stream_V_full_n(gray_data_stream_0_s_full_n),
    .gray_data_stream_V_write(normalized_U0_gray_data_stream_V_write),
    .max_dout(max_c_i_dout),
    .max_empty_n(max_c_i_empty_n),
    .max_read(normalized_U0_max_read),
    .min_dout(min_c_i_dout),
    .min_empty_n(min_c_i_empty_n),
    .min_read(normalized_U0_min_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_done(normalized_U0_ap_done),
    .ap_ready(normalized_U0_ap_ready),
    .ap_idle(normalized_U0_ap_idle),
    .ap_continue(normalized_U0_ap_continue)
);

Duplicate Duplicate_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Duplicate_U0_ap_start),
    .start_full_n(start_for_YCrCb_GUASSIAN_Loop_U0_full_n),
    .ap_done(Duplicate_U0_ap_done),
    .ap_continue(Duplicate_U0_ap_continue),
    .ap_idle(Duplicate_U0_ap_idle),
    .ap_ready(Duplicate_U0_ap_ready),
    .start_out(Duplicate_U0_start_out),
    .start_write(Duplicate_U0_start_write),
    .src_rows_V_dout(nor_copy1_rows_V_c_i_dout),
    .src_rows_V_empty_n(nor_copy1_rows_V_c_i_empty_n),
    .src_rows_V_read(Duplicate_U0_src_rows_V_read),
    .src_cols_V_dout(nor_copy1_cols_V_c_i_dout),
    .src_cols_V_empty_n(nor_copy1_cols_V_c_i_empty_n),
    .src_cols_V_read(Duplicate_U0_src_cols_V_read),
    .src_data_stream_V_dout(nor_copy1_data_strea_dout),
    .src_data_stream_V_empty_n(nor_copy1_data_strea_empty_n),
    .src_data_stream_V_read(Duplicate_U0_src_data_stream_V_read),
    .dst1_data_stream_V_din(Duplicate_U0_dst1_data_stream_V_din),
    .dst1_data_stream_V_full_n(nor_data_stream_V_full_n),
    .dst1_data_stream_V_write(Duplicate_U0_dst1_data_stream_V_write),
    .dst2_data_stream_V_din(Duplicate_U0_dst2_data_stream_V_din),
    .dst2_data_stream_V_full_n(nor_copy2_data_strea_full_n),
    .dst2_data_stream_V_write(Duplicate_U0_dst2_data_stream_V_write)
);

otsu_threshold otsu_threshold_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(otsu_threshold_U0_ap_start),
    .start_full_n(start_for_YCrCb_GUASSIAN_Block_U0_full_n),
    .ap_done(otsu_threshold_U0_ap_done),
    .ap_continue(otsu_threshold_U0_ap_continue),
    .ap_idle(otsu_threshold_U0_ap_idle),
    .ap_ready(otsu_threshold_U0_ap_ready),
    .start_out(otsu_threshold_U0_start_out),
    .start_write(otsu_threshold_U0_start_write),
    .gray_data_stream_V_dout(gray_data_stream_0_s_dout),
    .gray_data_stream_V_empty_n(gray_data_stream_0_s_empty_n),
    .gray_data_stream_V_read(otsu_threshold_U0_gray_data_stream_V_read),
    .ret_out_din(otsu_threshold_U0_ret_out_din),
    .ret_out_full_n(tmp3_c_i_full_n),
    .ret_out_write(otsu_threshold_U0_ret_out_write),
    .ret_out1_din(otsu_threshold_U0_ret_out1_din),
    .ret_out1_full_n(tmp3_c5_i_full_n),
    .ret_out1_write(otsu_threshold_U0_ret_out1_write)
);

YCrCb_GUASSIAN_Block YCrCb_GUASSIAN_Block_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(YCrCb_GUASSIAN_Block_U0_ap_start),
    .ap_done(YCrCb_GUASSIAN_Block_U0_ap_done),
    .ap_continue(YCrCb_GUASSIAN_Block_U0_ap_continue),
    .ap_idle(YCrCb_GUASSIAN_Block_U0_ap_idle),
    .ap_ready(YCrCb_GUASSIAN_Block_U0_ap_ready),
    .tmp3_dout(tmp3_c_i_dout),
    .tmp3_empty_n(tmp3_c_i_empty_n),
    .tmp3_read(YCrCb_GUASSIAN_Block_U0_tmp3_read),
    .threshold(YCrCb_GUASSIAN_Block_U0_threshold),
    .threshold_ap_vld(YCrCb_GUASSIAN_Block_U0_threshold_ap_vld)
);

YCrCb_GUASSIAN_Loop_s YCrCb_GUASSIAN_Loop_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(YCrCb_GUASSIAN_Loop_U0_ap_start),
    .start_full_n(start_for_erode_dilate_U0_full_n),
    .ap_done(YCrCb_GUASSIAN_Loop_U0_ap_done),
    .ap_continue(YCrCb_GUASSIAN_Loop_U0_ap_continue),
    .ap_idle(YCrCb_GUASSIAN_Loop_U0_ap_idle),
    .ap_ready(YCrCb_GUASSIAN_Loop_U0_ap_ready),
    .start_out(YCrCb_GUASSIAN_Loop_U0_start_out),
    .start_write(YCrCb_GUASSIAN_Loop_U0_start_write),
    .nor_copy2_data_stream_0_V_dout(nor_copy2_data_strea_dout),
    .nor_copy2_data_stream_0_V_empty_n(nor_copy2_data_strea_empty_n),
    .nor_copy2_data_stream_0_V_read(YCrCb_GUASSIAN_Loop_U0_nor_copy2_data_stream_0_V_read),
    .tmp3_dout(tmp3_c5_i_dout),
    .tmp3_empty_n(tmp3_c5_i_empty_n),
    .tmp3_read(YCrCb_GUASSIAN_Loop_U0_tmp3_read),
    .origin_data_stream_0_V_din(YCrCb_GUASSIAN_Loop_U0_origin_data_stream_0_V_din),
    .origin_data_stream_0_V_full_n(origin_data_stream_0_full_n),
    .origin_data_stream_0_V_write(YCrCb_GUASSIAN_Loop_U0_origin_data_stream_0_V_write)
);

erode_dilate erode_dilate_U0(
    .img_data_stream_V_dout(origin_data_stream_0_dout),
    .img_data_stream_V_empty_n(origin_data_stream_0_empty_n),
    .img_data_stream_V_read(erode_dilate_U0_img_data_stream_V_read),
    .res_data_stream_V_din(erode_dilate_U0_res_data_stream_V_din),
    .res_data_stream_V_full_n(res_data_stream_V_full_n),
    .res_data_stream_V_write(erode_dilate_U0_res_data_stream_V_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_done(erode_dilate_U0_ap_done),
    .ap_start(erode_dilate_U0_ap_start),
    .ap_ready(erode_dilate_U0_ap_ready),
    .ap_idle(erode_dilate_U0_ap_idle),
    .ap_continue(erode_dilate_U0_ap_continue)
);

fifo_w11_d6_A nor_copy1_rows_V_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(YCrCb_GUASSIAN_Block_2_U0_nor_copy1_rows_V_out_din),
    .if_full_n(nor_copy1_rows_V_c_i_full_n),
    .if_write(YCrCb_GUASSIAN_Block_2_U0_nor_copy1_rows_V_out_write),
    .if_dout(nor_copy1_rows_V_c_i_dout),
    .if_empty_n(nor_copy1_rows_V_c_i_empty_n),
    .if_read(Duplicate_U0_src_rows_V_read)
);

fifo_w10_d6_A nor_copy1_cols_V_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(YCrCb_GUASSIAN_Block_2_U0_nor_copy1_cols_V_out_din),
    .if_full_n(nor_copy1_cols_V_c_i_full_n),
    .if_write(YCrCb_GUASSIAN_Block_2_U0_nor_copy1_cols_V_out_write),
    .if_dout(nor_copy1_cols_V_c_i_dout),
    .if_empty_n(nor_copy1_cols_V_c_i_empty_n),
    .if_read(Duplicate_U0_src_cols_V_read)
);

fifo_w11_d3_A Sim_rows_V_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(YCrCb_GUASSIAN_Block_2_U0_Sim_rows_V_out_din),
    .if_full_n(Sim_rows_V_c_i_full_n),
    .if_write(YCrCb_GUASSIAN_Block_2_U0_Sim_rows_V_out_write),
    .if_dout(Sim_rows_V_c_i_dout),
    .if_empty_n(Sim_rows_V_c_i_empty_n),
    .if_read(Duplicate349_U0_src_rows_V_read)
);

fifo_w10_d3_A Sim_cols_V_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(YCrCb_GUASSIAN_Block_2_U0_Sim_cols_V_out_din),
    .if_full_n(Sim_cols_V_c_i_full_n),
    .if_write(YCrCb_GUASSIAN_Block_2_U0_Sim_cols_V_out_write),
    .if_dout(Sim_cols_V_c_i_dout),
    .if_empty_n(Sim_cols_V_c_i_empty_n),
    .if_read(Duplicate349_U0_src_cols_V_read)
);

fifo_w8_d1_A_x YCrCb_IMG_data_strea_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(CvtColor_U0_YCrCb_IMG_data_strea_i_din),
    .if_full_n(YCrCb_IMG_data_strea_full_n),
    .if_write(CvtColor_U0_YCrCb_IMG_data_strea_i_write),
    .if_dout(YCrCb_IMG_data_strea_dout),
    .if_empty_n(YCrCb_IMG_data_strea_empty_n),
    .if_read(Split_U0_src_data_stream_0_V_read)
);

fifo_w8_d1_A_x YCrCb_IMG_data_strea_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(CvtColor_U0_YCrCb_IMG_data_strea_1_i_din),
    .if_full_n(YCrCb_IMG_data_strea_1_full_n),
    .if_write(CvtColor_U0_YCrCb_IMG_data_strea_1_i_write),
    .if_dout(YCrCb_IMG_data_strea_1_dout),
    .if_empty_n(YCrCb_IMG_data_strea_1_empty_n),
    .if_read(Split_U0_src_data_stream_1_V_read)
);

fifo_w8_d1_A_x YCrCb_IMG_data_strea_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(CvtColor_U0_YCrCb_IMG_data_strea_2_i_din),
    .if_full_n(YCrCb_IMG_data_strea_2_full_n),
    .if_write(CvtColor_U0_YCrCb_IMG_data_strea_2_i_write),
    .if_dout(YCrCb_IMG_data_strea_2_dout),
    .if_empty_n(YCrCb_IMG_data_strea_2_empty_n),
    .if_read(Split_U0_src_data_stream_2_V_read)
);

fifo_w8_d1_A_x Cr_Img_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Split_U0_dst1_data_stream_V_din),
    .if_full_n(Cr_Img_data_stream_0_full_n),
    .if_write(Split_U0_dst1_data_stream_V_write),
    .if_dout(Cr_Img_data_stream_0_dout),
    .if_empty_n(Cr_Img_data_stream_0_empty_n),
    .if_read(YCrCb_GUASSIAN_Loop_1_U0_Cr_Img_data_stream_0_V_read)
);

fifo_w8_d1_A_x Cb_Img_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Split_U0_dst2_data_stream_V_din),
    .if_full_n(Cb_Img_data_stream_0_full_n),
    .if_write(Split_U0_dst2_data_stream_V_write),
    .if_dout(Cb_Img_data_stream_0_dout),
    .if_empty_n(Cb_Img_data_stream_0_empty_n),
    .if_read(YCrCb_GUASSIAN_Loop_1_U0_Cb_Img_data_stream_0_V_read)
);

fifo_w32_d1_A Sim_data_stream_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(YCrCb_GUASSIAN_Loop_1_U0_Sim_data_stream_0_V_din),
    .if_full_n(Sim_data_stream_0_V_full_n),
    .if_write(YCrCb_GUASSIAN_Loop_1_U0_Sim_data_stream_0_V_write),
    .if_dout(Sim_data_stream_0_V_dout),
    .if_empty_n(Sim_data_stream_0_V_empty_n),
    .if_read(Duplicate349_U0_src_data_stream_V_read)
);

fifo_w32_d1_A Sim_copy1_data_strea_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate349_U0_dst1_data_stream_V_din),
    .if_full_n(Sim_copy1_data_strea_full_n),
    .if_write(Duplicate349_U0_dst1_data_stream_V_write),
    .if_dout(Sim_copy1_data_strea_dout),
    .if_empty_n(Sim_copy1_data_strea_empty_n),
    .if_read(MinMaxLoc_U0_src_data_stream_V_read)
);

fifo_w32_d1_A Sim_copy2_data_strea_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate349_U0_dst2_data_stream_V_din),
    .if_full_n(Sim_copy2_data_strea_full_n),
    .if_write(Duplicate349_U0_dst2_data_stream_V_write),
    .if_dout(Sim_copy2_data_strea_dout),
    .if_empty_n(Sim_copy2_data_strea_empty_n),
    .if_read(normalized_U0_sim_data_stream_V_read)
);

fifo_w64_d1_A min_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MinMaxLoc_U0_min_val_out_din),
    .if_full_n(min_c_i_full_n),
    .if_write(MinMaxLoc_U0_min_val_out_write),
    .if_dout(min_c_i_dout),
    .if_empty_n(min_c_i_empty_n),
    .if_read(normalized_U0_min_read)
);

fifo_w64_d1_A max_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(MinMaxLoc_U0_max_val_out_din),
    .if_full_n(max_c_i_full_n),
    .if_write(MinMaxLoc_U0_max_val_out_write),
    .if_dout(max_c_i_dout),
    .if_empty_n(max_c_i_empty_n),
    .if_read(normalized_U0_max_read)
);

fifo_w32_d1_A nor_copy1_data_strea_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalized_U0_nor_data_stream_V_din),
    .if_full_n(nor_copy1_data_strea_full_n),
    .if_write(normalized_U0_nor_data_stream_V_write),
    .if_dout(nor_copy1_data_strea_dout),
    .if_empty_n(nor_copy1_data_strea_empty_n),
    .if_read(Duplicate_U0_src_data_stream_V_read)
);

fifo_w8_d1_A_x gray_data_stream_0_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalized_U0_gray_data_stream_V_din),
    .if_full_n(gray_data_stream_0_s_full_n),
    .if_write(normalized_U0_gray_data_stream_V_write),
    .if_dout(gray_data_stream_0_s_dout),
    .if_empty_n(gray_data_stream_0_s_empty_n),
    .if_read(otsu_threshold_U0_gray_data_stream_V_read)
);

fifo_w32_d1_A nor_copy2_data_strea_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst2_data_stream_V_din),
    .if_full_n(nor_copy2_data_strea_full_n),
    .if_write(Duplicate_U0_dst2_data_stream_V_write),
    .if_dout(nor_copy2_data_strea_dout),
    .if_empty_n(nor_copy2_data_strea_empty_n),
    .if_read(YCrCb_GUASSIAN_Loop_U0_nor_copy2_data_stream_0_V_read)
);

fifo_w64_d1_A tmp3_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(otsu_threshold_U0_ret_out_din),
    .if_full_n(tmp3_c_i_full_n),
    .if_write(otsu_threshold_U0_ret_out_write),
    .if_dout(tmp3_c_i_dout),
    .if_empty_n(tmp3_c_i_empty_n),
    .if_read(YCrCb_GUASSIAN_Block_U0_tmp3_read)
);

fifo_w64_d1_A tmp3_c5_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(otsu_threshold_U0_ret_out1_din),
    .if_full_n(tmp3_c5_i_full_n),
    .if_write(otsu_threshold_U0_ret_out1_write),
    .if_dout(tmp3_c5_i_dout),
    .if_empty_n(tmp3_c5_i_empty_n),
    .if_read(YCrCb_GUASSIAN_Loop_U0_tmp3_read)
);

fifo_w8_d1_A_x origin_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(YCrCb_GUASSIAN_Loop_U0_origin_data_stream_0_V_din),
    .if_full_n(origin_data_stream_0_full_n),
    .if_write(YCrCb_GUASSIAN_Loop_U0_origin_data_stream_0_V_write),
    .if_dout(origin_data_stream_0_dout),
    .if_empty_n(origin_data_stream_0_empty_n),
    .if_read(erode_dilate_U0_img_data_stream_V_read)
);

start_for_Split_U0 start_for_Split_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Split_U0_din),
    .if_full_n(start_for_Split_U0_full_n),
    .if_write(CvtColor_U0_start_write),
    .if_dout(start_for_Split_U0_dout),
    .if_empty_n(start_for_Split_U0_empty_n),
    .if_read(Split_U0_ap_ready)
);

start_for_YCrCb_GBew start_for_YCrCb_GBew_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_YCrCb_GUASSIAN_Loop_1_U0_din),
    .if_full_n(start_for_YCrCb_GUASSIAN_Loop_1_U0_full_n),
    .if_write(Split_U0_start_write),
    .if_dout(start_for_YCrCb_GUASSIAN_Loop_1_U0_dout),
    .if_empty_n(start_for_YCrCb_GUASSIAN_Loop_1_U0_empty_n),
    .if_read(YCrCb_GUASSIAN_Loop_1_U0_ap_ready)
);

start_for_DuplicaCeG start_for_DuplicaCeG_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Duplicate349_U0_din),
    .if_full_n(start_for_Duplicate349_U0_full_n),
    .if_write(YCrCb_GUASSIAN_Loop_1_U0_start_write),
    .if_dout(start_for_Duplicate349_U0_dout),
    .if_empty_n(start_for_Duplicate349_U0_empty_n),
    .if_read(Duplicate349_U0_ap_ready)
);

start_for_MinMaxLDeQ start_for_MinMaxLDeQ_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_MinMaxLoc_U0_din),
    .if_full_n(start_for_MinMaxLoc_U0_full_n),
    .if_write(Duplicate349_U0_start_write),
    .if_dout(start_for_MinMaxLoc_U0_dout),
    .if_empty_n(start_for_MinMaxLoc_U0_empty_n),
    .if_read(MinMaxLoc_U0_ap_ready)
);

start_for_normaliEe0 start_for_normaliEe0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalized_U0_din),
    .if_full_n(start_for_normalized_U0_full_n),
    .if_write(Duplicate349_U0_start_write),
    .if_dout(start_for_normalized_U0_dout),
    .if_empty_n(start_for_normalized_U0_empty_n),
    .if_read(normalized_U0_ap_ready)
);

start_for_DuplicaFfa start_for_DuplicaFfa_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Duplicate_U0_din),
    .if_full_n(start_for_Duplicate_U0_full_n),
    .if_write(normalized_U0_start_write),
    .if_dout(start_for_Duplicate_U0_dout),
    .if_empty_n(start_for_Duplicate_U0_empty_n),
    .if_read(Duplicate_U0_ap_ready)
);

start_for_otsu_thGfk start_for_otsu_thGfk_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_otsu_threshold_U0_din),
    .if_full_n(start_for_otsu_threshold_U0_full_n),
    .if_write(normalized_U0_start_write),
    .if_dout(start_for_otsu_threshold_U0_dout),
    .if_empty_n(start_for_otsu_threshold_U0_empty_n),
    .if_read(otsu_threshold_U0_ap_ready)
);

start_for_YCrCb_GHfu start_for_YCrCb_GHfu_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_YCrCb_GUASSIAN_Loop_U0_din),
    .if_full_n(start_for_YCrCb_GUASSIAN_Loop_U0_full_n),
    .if_write(Duplicate_U0_start_write),
    .if_dout(start_for_YCrCb_GUASSIAN_Loop_U0_dout),
    .if_empty_n(start_for_YCrCb_GUASSIAN_Loop_U0_empty_n),
    .if_read(YCrCb_GUASSIAN_Loop_U0_ap_ready)
);

start_for_YCrCb_GIfE start_for_YCrCb_GIfE_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_YCrCb_GUASSIAN_Block_U0_din),
    .if_full_n(start_for_YCrCb_GUASSIAN_Block_U0_full_n),
    .if_write(otsu_threshold_U0_start_write),
    .if_dout(start_for_YCrCb_GUASSIAN_Block_U0_dout),
    .if_empty_n(start_for_YCrCb_GUASSIAN_Block_U0_empty_n),
    .if_read(YCrCb_GUASSIAN_Block_U0_ap_ready)
);

start_for_erode_dJfO start_for_erode_dJfO_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_erode_dilate_U0_din),
    .if_full_n(start_for_erode_dilate_U0_full_n),
    .if_write(YCrCb_GUASSIAN_Loop_U0_start_write),
    .if_dout(start_for_erode_dilate_U0_dout),
    .if_empty_n(start_for_erode_dilate_U0_empty_n),
    .if_read(erode_dilate_U0_ap_ready)
);

assign CvtColor_U0_ap_continue = 1'b1;

assign CvtColor_U0_ap_start = ap_start;

assign Duplicate349_U0_ap_continue = 1'b1;

assign Duplicate349_U0_ap_start = start_for_Duplicate349_U0_empty_n;

assign Duplicate349_U0_start_full_n = (start_for_normalized_U0_full_n & start_for_MinMaxLoc_U0_full_n);

assign Duplicate_U0_ap_continue = ap_sync_continue;

assign Duplicate_U0_ap_start = start_for_Duplicate_U0_empty_n;

assign MinMaxLoc_U0_ap_continue = 1'b1;

assign MinMaxLoc_U0_ap_start = start_for_MinMaxLoc_U0_empty_n;

assign MinMaxLoc_U0_start_full_n = 1'b1;

assign MinMaxLoc_U0_start_write = 1'b0;

assign Split_U0_ap_continue = 1'b1;

assign Split_U0_ap_start = start_for_Split_U0_empty_n;

assign YCrCb_GUASSIAN_Block_2_U0_ap_continue = 1'b1;

assign YCrCb_GUASSIAN_Block_2_U0_ap_start = ap_start;

assign YCrCb_GUASSIAN_Block_2_U0_start_full_n = 1'b1;

assign YCrCb_GUASSIAN_Block_2_U0_start_write = 1'b0;

assign YCrCb_GUASSIAN_Block_U0_ap_continue = ap_sync_continue;

assign YCrCb_GUASSIAN_Block_U0_ap_start = start_for_YCrCb_GUASSIAN_Block_U0_empty_n;

assign YCrCb_GUASSIAN_Block_U0_start_full_n = 1'b1;

assign YCrCb_GUASSIAN_Block_U0_start_write = 1'b0;

assign YCrCb_GUASSIAN_Loop_1_U0_ap_continue = 1'b1;

assign YCrCb_GUASSIAN_Loop_1_U0_ap_start = start_for_YCrCb_GUASSIAN_Loop_1_U0_empty_n;

assign YCrCb_GUASSIAN_Loop_U0_ap_continue = 1'b1;

assign YCrCb_GUASSIAN_Loop_U0_ap_start = start_for_YCrCb_GUASSIAN_Loop_U0_empty_n;

assign ap_done = ap_sync_done;

assign ap_idle = (otsu_threshold_U0_ap_idle & normalized_U0_ap_idle & erode_dilate_U0_ap_idle & YCrCb_GUASSIAN_Loop_U0_ap_idle & YCrCb_GUASSIAN_Loop_1_U0_ap_idle & YCrCb_GUASSIAN_Block_U0_ap_idle & YCrCb_GUASSIAN_Block_2_U0_ap_idle & Split_U0_ap_idle & MinMaxLoc_U0_ap_idle & Duplicate_U0_ap_idle & Duplicate349_U0_ap_idle & CvtColor_U0_ap_idle);

assign ap_ready = CvtColor_U0_ap_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (erode_dilate_U0_ap_done & YCrCb_GUASSIAN_Block_U0_ap_done & Duplicate_U0_ap_done);

assign ap_sync_ready = CvtColor_U0_ap_ready;

assign erode_dilate_U0_ap_continue = ap_sync_continue;

assign erode_dilate_U0_ap_start = start_for_erode_dilate_U0_empty_n;

assign erode_dilate_U0_start_full_n = 1'b1;

assign erode_dilate_U0_start_write = 1'b0;

assign nor_data_stream_V_din = Duplicate_U0_dst1_data_stream_V_din;

assign nor_data_stream_V_write = Duplicate_U0_dst1_data_stream_V_write;

assign normalized_U0_ap_continue = 1'b1;

assign normalized_U0_ap_start = start_for_normalized_U0_empty_n;

assign normalized_U0_start_full_n = (start_for_otsu_threshold_U0_full_n & start_for_Duplicate_U0_full_n);

assign otsu_threshold_U0_ap_continue = 1'b1;

assign otsu_threshold_U0_ap_start = start_for_otsu_threshold_U0_empty_n;

assign res_data_stream_V_din = erode_dilate_U0_res_data_stream_V_din;

assign res_data_stream_V_write = erode_dilate_U0_res_data_stream_V_write;

assign src_data_stream_0_V_read = CvtColor_U0_src_mat_data_stream_s_read;

assign src_data_stream_1_V_read = CvtColor_U0_src_mat_data_stream_1_read;

assign src_data_stream_2_V_read = CvtColor_U0_src_mat_data_stream_2_read;

assign start_for_Duplicate349_U0_din = 1'b1;

assign start_for_Duplicate_U0_din = 1'b1;

assign start_for_MinMaxLoc_U0_din = 1'b1;

assign start_for_Split_U0_din = 1'b1;

assign start_for_YCrCb_GUASSIAN_Block_U0_din = 1'b1;

assign start_for_YCrCb_GUASSIAN_Loop_1_U0_din = 1'b1;

assign start_for_YCrCb_GUASSIAN_Loop_U0_din = 1'b1;

assign start_for_erode_dilate_U0_din = 1'b1;

assign start_for_normalized_U0_din = 1'b1;

assign start_for_otsu_threshold_U0_din = 1'b1;

assign threshold = YCrCb_GUASSIAN_Block_U0_threshold;

assign threshold_ap_vld = YCrCb_GUASSIAN_Block_U0_threshold_ap_vld;

endmodule //YCrCb_GUASSIAN
