#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("input_r_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("input_r_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("input_r_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("input_r_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("input_r_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("input_r_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("input_r_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("output_r_TDATA", 32, hls_out, 7, "axis", "out_data", 1),
	Port_Property("output_r_TKEEP", 4, hls_out, 8, "axis", "out_data", 1),
	Port_Property("output_r_TSTRB", 4, hls_out, 9, "axis", "out_data", 1),
	Port_Property("output_r_TUSER", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("output_r_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("output_r_TID", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("output_r_TDEST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("nor_output_TDATA", 32, hls_out, 14, "axis", "out_data", 1),
	Port_Property("nor_output_TKEEP", 4, hls_out, 15, "axis", "out_data", 1),
	Port_Property("nor_output_TSTRB", 4, hls_out, 16, "axis", "out_data", 1),
	Port_Property("nor_output_TUSER", 1, hls_out, 17, "axis", "out_data", 1),
	Port_Property("nor_output_TLAST", 1, hls_out, 18, "axis", "out_data", 1),
	Port_Property("nor_output_TID", 1, hls_out, 19, "axis", "out_data", 1),
	Port_Property("nor_output_TDEST", 1, hls_out, 20, "axis", "out_data", 1),
	Port_Property("rows", 32, hls_in, 21, "ap_stable", "in_data", 1),
	Port_Property("cols", 32, hls_in, 22, "ap_stable", "in_data", 1),
	Port_Property("threshold", 64, hls_out, 23, "ap_vld", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("input_r_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("input_r_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("threshold_ap_vld", 1, hls_out, 23, "ap_vld", "out_vld", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("output_r_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("output_r_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
	Port_Property("nor_output_TVALID", 1, hls_out, 20, "axis", "out_vld", 1),
	Port_Property("nor_output_TREADY", 1, hls_in, 20, "axis", "out_acc", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "ImgProcess_Top";
