-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity normalized is
port (
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    sim_data_stream_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    sim_data_stream_V_empty_n : IN STD_LOGIC;
    sim_data_stream_V_read : OUT STD_LOGIC;
    nor_data_stream_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    nor_data_stream_V_full_n : IN STD_LOGIC;
    nor_data_stream_V_write : OUT STD_LOGIC;
    gray_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    gray_data_stream_V_full_n : IN STD_LOGIC;
    gray_data_stream_V_write : OUT STD_LOGIC;
    max_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    max_empty_n : IN STD_LOGIC;
    max_read : OUT STD_LOGIC;
    min_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    min_empty_n : IN STD_LOGIC;
    min_read : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of normalized is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal internal_ap_ready : STD_LOGIC;
    signal normalized_Loop_loop_U0_ap_start : STD_LOGIC;
    signal normalized_Loop_loop_U0_ap_done : STD_LOGIC;
    signal normalized_Loop_loop_U0_ap_continue : STD_LOGIC;
    signal normalized_Loop_loop_U0_ap_idle : STD_LOGIC;
    signal normalized_Loop_loop_U0_ap_ready : STD_LOGIC;
    signal normalized_Loop_loop_U0_max_read : STD_LOGIC;
    signal normalized_Loop_loop_U0_min_read : STD_LOGIC;
    signal normalized_Loop_loop_U0_sim_data_stream_V_read : STD_LOGIC;
    signal normalized_Loop_loop_U0_nor_data_stream_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal normalized_Loop_loop_U0_nor_data_stream_V_write : STD_LOGIC;
    signal normalized_Loop_loop_U0_gray_data_stream_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal normalized_Loop_loop_U0_gray_data_stream_V_write : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal normalized_Loop_loop_U0_start_full_n : STD_LOGIC;
    signal normalized_Loop_loop_U0_start_write : STD_LOGIC;

    component normalized_Loop_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        max_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        max_empty_n : IN STD_LOGIC;
        max_read : OUT STD_LOGIC;
        min_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        min_empty_n : IN STD_LOGIC;
        min_read : OUT STD_LOGIC;
        sim_data_stream_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sim_data_stream_V_empty_n : IN STD_LOGIC;
        sim_data_stream_V_read : OUT STD_LOGIC;
        nor_data_stream_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        nor_data_stream_V_full_n : IN STD_LOGIC;
        nor_data_stream_V_write : OUT STD_LOGIC;
        gray_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        gray_data_stream_V_full_n : IN STD_LOGIC;
        gray_data_stream_V_write : OUT STD_LOGIC );
    end component;



begin
    normalized_Loop_loop_U0 : component normalized_Loop_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => normalized_Loop_loop_U0_ap_start,
        ap_done => normalized_Loop_loop_U0_ap_done,
        ap_continue => normalized_Loop_loop_U0_ap_continue,
        ap_idle => normalized_Loop_loop_U0_ap_idle,
        ap_ready => normalized_Loop_loop_U0_ap_ready,
        max_dout => max_dout,
        max_empty_n => max_empty_n,
        max_read => normalized_Loop_loop_U0_max_read,
        min_dout => min_dout,
        min_empty_n => min_empty_n,
        min_read => normalized_Loop_loop_U0_min_read,
        sim_data_stream_V_dout => sim_data_stream_V_dout,
        sim_data_stream_V_empty_n => sim_data_stream_V_empty_n,
        sim_data_stream_V_read => normalized_Loop_loop_U0_sim_data_stream_V_read,
        nor_data_stream_V_din => normalized_Loop_loop_U0_nor_data_stream_V_din,
        nor_data_stream_V_full_n => nor_data_stream_V_full_n,
        nor_data_stream_V_write => normalized_Loop_loop_U0_nor_data_stream_V_write,
        gray_data_stream_V_din => normalized_Loop_loop_U0_gray_data_stream_V_din,
        gray_data_stream_V_full_n => gray_data_stream_V_full_n,
        gray_data_stream_V_write => normalized_Loop_loop_U0_gray_data_stream_V_write);





    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= normalized_Loop_loop_U0_ap_done;
    ap_idle <= normalized_Loop_loop_U0_ap_idle;
    ap_ready <= internal_ap_ready;
    ap_sync_continue <= ap_continue;
    ap_sync_done <= normalized_Loop_loop_U0_ap_done;
    ap_sync_ready <= normalized_Loop_loop_U0_ap_ready;
    gray_data_stream_V_din <= normalized_Loop_loop_U0_gray_data_stream_V_din;
    gray_data_stream_V_write <= normalized_Loop_loop_U0_gray_data_stream_V_write;
    internal_ap_ready <= ap_sync_ready;
    max_read <= normalized_Loop_loop_U0_max_read;
    min_read <= normalized_Loop_loop_U0_min_read;
    nor_data_stream_V_din <= normalized_Loop_loop_U0_nor_data_stream_V_din;
    nor_data_stream_V_write <= normalized_Loop_loop_U0_nor_data_stream_V_write;
    normalized_Loop_loop_U0_ap_continue <= ap_continue;
    normalized_Loop_loop_U0_ap_start <= real_start;
    normalized_Loop_loop_U0_start_full_n <= ap_const_logic_1;
    normalized_Loop_loop_U0_start_write <= ap_const_logic_0;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    sim_data_stream_V_read <= normalized_Loop_loop_U0_sim_data_stream_V_read;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
